Repository edgelesssys/contrast, pull requests merged in 2024-12, with the labels that each got.

#1042 overlays: bump treefmt to 2.1.1
  overlays/nixpkgs.nix
Labels: no changelog

#1026 deps: update pinned rpm packages
  packages/by-name/kata/kata-image/package-index.json
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1030 sdk: move verify code into sdk
  .golangci.yml
  .vscode/settings.json
  cli/cmd/common.go
  cli/cmd/recover.go
  cli/cmd/set.go
  cli/cmd/verify.go
  packages/by-name/contrast/package.nix
  sdk/README.md
  sdk/common.go
  sdk/sdk.go
  sdk/verify.go
  sdk/verify_test.go
Labels: no changelog

#1053 cli: fix nondeterministic policy generation
  e2e/policy/deterministic_test.go
  packages/by-name/kata/kata-runtime/0004-genpolicy-enable-sysctl-checks.patch
  packages/by-name/kata/kata-runtime/0009-genpolicy-allow-image_guest_pull.patch
Labels: bug fix

#1036 sdk: remove Linux dependencies
  coordinator/main.go
  initializer/main.go
  internal/atls/issuer/issuer_linux.go
  internal/atls/issuer/issuer_universal.go
  internal/attestation/snp/issuer/issuer.go
  internal/attestation/snp/issuer/thim.go
  internal/attestation/tdx/issuer/issuer.go
Labels: no changelog

#986 node-installer: write kata config with less perms
  cli/cmd/generate.go
  cli/genpolicy/genpolicy.go
  internal/embedbin/regular.go
  internal/fsstore/fsstore.go
  nodeinstaller/node-installer.go
Labels: no changelog

#1054 cli/genpolicy: by default do not include log-level 'debug' in Contras…
  cli/genpolicy/genpolicy.go
Labels: bug fix

#1062 kata-image: allow remount service to manage /run
  packages/nixos/system.nix
Labels: no changelog

#1063 license: add enterprise
  LICENSE
  LICENSE.AGPL
  README.md
  enterprise/LICENSE
  enterprise/README.md
Labels: no changelog

#1066 packages/nixos: minimize image size
  packages/nixos/kata.nix
  packages/nixos/system.nix
Labels: no changelog

#1050 kds-cache: add fallback cache for CRLs on request failure
  internal/attestation/certcache/cached_client.go
  internal/attestation/certcache/cached_client_test.go
Labels: changelog

#1070 ci: don't update RPMs for Kata image
  .github/workflows/rpm_updates.yml
Labels: no changelog

#1067 ci: correctly trigger peerpods e2e on image changes
  .github/workflows/e2e_peerpods.yml
Labels: no changelog

#1072 caa: adjust peer-pod image to immutable /etc
  packages/by-name/kernel-podvm-azure/0001-azure-fix-sublevel.patch
  packages/by-name/kernel-podvm-azure/package.nix
  packages/by-name/mkNixosConfig/package.nix
  packages/nixos/azure.nix
  packages/nixos/peerpods.nix
Labels: no changelog

#1058 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1074 node-installer: add test for kata config
  nodeinstaller/internal/config/kata_runtime.go
  nodeinstaller/internal/config/kata_runtime_test.go
  nodeinstaller/node-installer.go
Labels: no changelog

#1079 deps: downgrade softprops/action-gh-release to v2.1.0
  .github/workflows/release.yml
Labels: no changelog

#1080 kds-cache: adjust cache expiration time to 9 months
  coordinator/internal/authority/credentials.go
Labels: no changelog

#1081 kuberesource: pin container images for emojivoto/mysql demo by hash
  internal/kuberesource/sets.go
Labels: bug fix, backport release/v1.2

#1084 [release/v1.2] kuberesource: pin container images for emojivoto/mysql demo by hash
  internal/kuberesource/sets.go
Labels: bug fix

#927 qemu-static: add patches for VFIO support on SNP
  packages/by-name/qemu-static/0003-guest_memfd-Introduce-an-object-to-manage-the-guest-.patch
  packages/by-name/qemu-static/0004-guest_memfd-Introduce-a-helper-to-notify-the-shared-.patch
  packages/by-name/qemu-static/0005-KVM-Notify-the-state-change-via-RamDiscardManager-he.patch
  packages/by-name/qemu-static/0006-memory-Register-the-RamDiscardManager-instance-upon-.patch
  packages/by-name/qemu-static/0007-guest-memfd-Default-to-discarded-private-in-guest_me.patch
  packages/by-name/qemu-static/0008-RAMBlock-make-guest_memfd-require-coordinate-discard.patch
  packages/by-name/qemu-static/0009-increase-min-granularity-for-memfd.patch
  packages/by-name/qemu-static/package.nix
Labels: no changelog

#1087 packages/nixos: write Kata agent output to console and journal
  packages/nixos/kata.nix
Labels: no changelog

#1090 packages/kata-runtime: add guest hook support to genpolicy
  packages/by-name/kata/kata-runtime/0020-genpolicy-support-guest-hooks.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: no changelog

#1082 attestation.snp: reflect dependency of validators on productLine in verify.Options
  internal/manifest/manifest.go
Labels: bug fix, backport release/v1.2

#1097 [release/v1.2] attestation.snp: reflect dependency of validators on productLine in verify.Options
  internal/manifest/manifest.go
Labels: bug fix

#1096 nixos/image: use erofs-utils' --hard-dereference flag
  packages/nixos/image.nix
Labels: changelog

#1088 packages/kata-kernel: add GPU variant
  packages/by-name/kata/kata-kernel-uvm/package.nix
Labels: no changelog

#1100 e2e: create DynamicClient directly
  e2e/internal/kubeclient/deploy.go
  e2e/internal/kubeclient/kubeclient.go
Labels: no changelog, backport release/v1.2

#1101 [release/v1.2] e2e: create DynamicClient directly
  e2e/internal/kubeclient/deploy.go
  e2e/internal/kubeclient/kubeclient.go
Labels: no changelog

#1107 release: publish runtime.yml for metal platforms
  .github/workflows/release.yml
  packages/scripts.nix
Labels: bug fix, backport release/v1.2

#1110 contrast-releases: add mysql demo and runtime.yml for metal platforms
  packages/contrast-releases.json
  packages/contrast-releases.nix
  packages/update-contrast-releases.sh
Labels: no changelog, backport release/v1.2

#1109 [release/v1.2] release: publish runtime.yml for metal platforms
  .github/workflows/release.yml
  packages/scripts.nix
Labels: bug fix

#1111 [release/v1.2] contrast-releases: add mysql demo and runtime.yml for metal platforms
  packages/contrast-releases.json
  packages/contrast-releases.nix
  packages/update-contrast-releases.sh
Labels: no changelog
