Repository edgelesssys/contrast, pull requests merged in 2024-05, with the labels that each got.

#481 readme: improve language
  README.md
Labels: no changelog

#477 coordinator: add manifest generation metric
  coordinator/userapi.go
  coordinator/userapi_test.go
  docs/docs/architecture/observability.md
Labels: changelog

#482 docs: fix download link
  docs/docs/deployment.md
  docs/docs/getting-started/install.md
  docs/versioned_docs/version-0.5/deployment.md
  docs/versioned_docs/version-0.5/getting-started/install.md
  docs/versioned_docs/version-0.6/deployment.md
  docs/versioned_docs/version-0.6/getting-started/install.md
Labels: no changelog

#464 genpolicy-msft: bump version to 3.2.0.azl1.genpolicy0
  packages/by-name/genpolicy-msft/genpolicy_msft_rules_coordinator.patch
  packages/by-name/genpolicy-msft/genpolicy_msft_settings_dev.patch
  packages/by-name/genpolicy-msft/package.nix
Labels: dependencies

#484 coordinator: add metric for attestation failures with error string
  coordinator/meshapi.go
  docs/docs/architecture/observability.md
  internal/attestation/snp/validator.go
Labels: changelog

#490 resourcegen: settle on one set for the Coordinator
  e2e/openssl/openssl_test.go
  e2e/servicemesh/servicemesh_test.go
  internal/kuberesource/resourcegen/main.go
  internal/kuberesource/sets.go
  packages/scripts.nix
Labels: no changelog

#498 docs: harden curl invocation in installation instruction
  docs/docs/getting-started/install.md
Labels: documentation

#500 docs: add curl hardening flags for released version
  docs/versioned_docs/version-0.6/getting-started/install.md
Labels: no changelog

#501 coordinator: add grpc latency metrics
  coordinator/meshapi.go
  coordinator/userapi.go
  docs/docs/architecture/observability.md
Labels: changelog

#502 coordinator: prefix metrics with contrast
  coordinator/meshapi.go
  coordinator/userapi.go
  docs/docs/architecture/observability.md
Labels: no changelog

#496 genpolicy-msft: add support for volumeDevices
  packages/by-name/genpolicy-msft/package.nix
Labels: changelog

#492 tools: add prometheus ci deployment.yml
  tools/prometheus-ci/deployment.yml
Labels: no changelog

#508 packages: minor nix cleanup
  packages/by-name/buildGoTest/package.nix
  packages/by-name/contrast-node-installer-image/package.nix
  packages/by-name/contrast-node-installer/package.nix
  packages/by-name/contrast/package.nix
  packages/by-name/genpolicy-kata/package.nix
  packages/by-name/igvm-signing-keygen/package.nix
  packages/by-name/igvm-tooling/package.nix
  packages/by-name/igvmmeasure/package.nix
  packages/by-name/kata-agent/package.nix
  packages/by-name/kata-igvm/package.nix
  packages/by-name/kata-image/package.nix
  packages/by-name/kata-kernel-uvm/package.nix
  packages/by-name/kata-runtime/package.nix
  packages/by-name/ociImageConfig/package.nix
  packages/by-name/ociImageLayout/package.nix
  packages/by-name/ociImageManifest/package.nix
  packages/by-name/ociLayerTar/package.nix
  packages/by-name/rpm-pin-vendor/package.nix
  packages/by-name/runtime-class-files/package.nix
  packages/by-name/service-mesh/package.nix
  packages/containers.nix
  packages/scripts.nix
Labels: no changelog

#491 coordinator: make metrics endpoint configurable
  coordinator/main.go
  docs/docs/architecture/observability.md
  e2e/internal/contrasttest/contrasttest.go
  e2e/openssl/openssl_test.go
  internal/kuberesource/mutators.go
  internal/kuberesource/parts.go
Labels: changelog
