Repository edgelesssys/contrast, pull requests merged in 2024-08, with the labels that each got.

#778 scripts.generate: remove update of node-installer vendorHash
  packages/scripts.nix
Labels: no changelog

#769 kata-agent: always use 256-bit hashes and never skip policy validation
  packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: no changelog

#779 coordinator: correct shutdown, report serve errors
  coordinator/main.go
Labels: bug fix, backport release/v0.8

#771 genpolicy: hide logs by default
  packages/by-name/microsoft/genpolicy/genpolicy_msft_settings_prod.patch
  packages/by-name/microsoft/genpolicy/package.nix
Labels: breaking change

#785 manifest: add WorkloadSecretID field
  cli/cmd/policies.go
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/authority_test.go
  coordinator/internal/authority/userapi_test.go
  e2e/openssl/openssl_test.go
  e2e/policy/policy_test.go
  internal/manifest/manifest.go
  internal/manifest/manifest_test.go
Labels: breaking change

#786 node-installer: only replace runtimeName in paths
  nodeinstaller/internal/constants/constants.go
  nodeinstaller/node-installer.go
  packages/by-name/kata/contrast-node-installer-image/package.nix
  packages/by-name/microsoft/contrast-node-installer-image/package.nix
Labels: no changelog

#784 resourcegen: always use https startup probe for web pod
  internal/kuberesource/sets.go
Labels: no changelog

#761 rfc: genpolicy on diverse platforms
  rfc/006-genpolicy-platforms.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#777 rfc: workload secrets
  rfc/007-workload-secrets.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#787 ci: use btrfs for all Nix builds
  .github/actions/nix_tmpfs/action.yml
  .github/actions/setup_nix/action.yml
  .github/workflows/e2e_openssl.yml
  .github/workflows/e2e_policy.yml
  .github/workflows/e2e_regression.yml
  .github/workflows/e2e_servicemesh.yml
  .github/workflows/static.yml
Labels: no changelog

#792 just: credential getter as nix script
  justfile
  packages/scripts.nix
Labels: no changelog

#794 release: pin tardev-snapshotter image
  .github/workflows/release.yml
Labels: no changelog

#795 release: set platform for resourcegen
  internal/kuberesource/resourcegen/main.go
  packages/scripts.nix
Labels: no changelog

#790 docs: animated banner
  README.md
  docs/static/img/GitHub-Banner_Contrast_2024.gif
  docs/static/img/banner.svg
Labels: no changelog

#791 coordinator: pass state as AuthInfo to meshapi
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/authority_test.go
  coordinator/internal/authority/credentials.go
  coordinator/internal/authority/userapi.go
  coordinator/main.go
  coordinator/meshapi.go
Labels: no changelog

#800 just: deploy node-installer in namespace
  justfile
Labels: no changelog

#799 nydus-snapshotter: 0.13.13 -> 0.13.14
  packages/by-name/nydus-snapshotter/package.nix
Labels: no changelog

#803 authority: remove unused Bundle struct
  coordinator/internal/authority/authority.go
Labels: no changelog

#802 dev-docs: describe policy debugging strategy
  dev-docs/coco/policy.md
Labels: no changelog

#801 runtime-class-files: remove, calculate runtime hash from all files
  packages/by-name/contrast/package.nix
  packages/by-name/hashDirs/package.nix
  packages/by-name/kata/contrast-node-installer-image/package.nix
  packages/by-name/kata/runtime-class-files/package.nix
  packages/by-name/microsoft/contrast-node-installer-image/package.nix
  packages/by-name/microsoft/kata-igvm/package.nix
  packages/by-name/microsoft/runtime-class-files/package.nix
  packages/by-name/ociImageLayout/package.nix
  packages/by-name/qemu-tdx-bin/package.nix
Labels: no changelog

#804 ci: combine kubernetes e2e tests in one matrix workflow
  .github/workflows/e2e_kubernetes.yaml
  .github/workflows/e2e_policy.yml
  .github/workflows/e2e_servicemesh.yml
Labels: no changelog

#783 treewide: allow multiple validators
  cli/cmd/common.go
  cli/cmd/recover.go
  cli/cmd/set.go
  cli/cmd/verify.go
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/authority_test.go
  coordinator/internal/authority/credentials.go
  initializer/main.go
  internal/atls/atls.go
  internal/attestation/snp/validator.go
  internal/grpc/dialer/dialer.go
  internal/manifest/constants.go
  internal/manifest/manifest.go
  internal/manifest/manifest_test.go
  internal/manifest/referencevalues.go
  packages/by-name/contrast/package.nix
Labels: no changelog

#808 node-installer: fix debug output on aks-clh-snp
  nodeinstaller/internal/constants/constants.go
Labels: no changelog

#810 node-installer: fix debug config
  nodeinstaller/internal/constants/constants.go
Labels: no changelog

#812 e2e: specify multiple reference values in openssl test
  e2e/openssl/openssl_test.go
Labels: no changelog

#813 atls: only report attestation error if all validators fail
  cli/cmd/recover.go
  cli/cmd/set.go
  cli/cmd/verify.go
  coordinator/internal/authority/credentials.go
  coordinator/main.go
  initializer/main.go
  internal/atls/atls.go
  internal/attestation/snp/validator.go
  internal/grpc/atlscredentials/atlscredentials.go
  internal/grpc/dialer/dialer.go
Labels: no changelog

#820 ci: always cleanup runner, create nix builder volume under /mnt
  .github/actions/setup_nix/action.yml
  .github/workflows/static.yml
Labels: no changelog

#797 e2e: improve the regression test
  .github/workflows/e2e_regression.yml
  e2e/internal/kubeclient/deploy.go
  e2e/internal/kubeclient/kubeclient.go
  e2e/internal/kubeclient/portforward.go
  e2e/regression/README.md
  e2e/regression/regression_test.go
  e2e/regression/testdata/apache-httpd-centos.yaml
  e2e/regression/testdata/apache-httpd-fedora.yaml
  e2e/regression/testdata/keycloak.yaml
  e2e/regression/testdata/mongodb.yaml
  e2e/regression/testdata/mysql-centos.yaml
  e2e/regression/testdata/mysql-fedora.yaml
  e2e/regression/testdata/nginx.yaml
  e2e/regression/testdata/prometheus.yaml
  e2e/regression/testdata/redis.yaml
  e2e/regression/testdata/varnish.yaml
  internal/kuberesource/constants.go
  packages/by-name/contrast/package.nix
Labels: no changelog

#821 just: fix deploy after undeploy
  justfile
Labels: no changelog

#828 docs: enable broken anchor detection
  docs/docusaurus.config.js
Labels: no changelog

#829 resourcegen: enable adding dmesg container
  internal/kuberesource/mutators.go
  internal/kuberesource/resourcegen/main.go
  justfile
  packages/containers.nix
Labels: no changelog

#832 nydus-snapshotter: disable database flock timeout
  packages/by-name/nydus-snapshotter/0001-disable-database-flock-timeout.patch
  packages/by-name/nydus-snapshotter/package.nix
Labels: no changelog

#836 certcache: don't cache CRL URLs
  internal/attestation/certcache/cached_client.go
Labels: no changelog

#811 nix: bump reference values for SNP on AKS
  packages/by-name/contrast/package.nix
Labels: breaking change

#838 ci: don't fail fast
  .github/workflows/e2e_kubernetes.yaml
  .github/workflows/e2e_openssl_baremetal.yml
  .github/workflows/e2e_regression.yml
Labels: no changelog

#839 Revert "nix: bump reference values for SNP on AKS"
  packages/by-name/contrast/package.nix
Labels: no changelog

#841 e2e: fix regression cleanup
  e2e/regression/regression_test.go
Labels: no changelog

#840 e2e: try a little harder to delete the namespace
  e2e/internal/contrasttest/contrasttest.go
Labels: no changelog

#834 kata.kata-image: don't include tdnf/history.db
  packages/by-name/kata/kata-image/package.nix
Labels: no changelog

#844 kata.{kata-runtime,kata-agent,kata-image,genpolicy}: 3.7.0 -> 3.8.0
  packages/by-name/kata/kata-agent/0001-runtime-agent-mounts-Mount-configfs-into-the-contain.patch
  packages/by-name/kata/kata-agent/package.nix
  packages/by-name/kata/kata-runtime/0001-govmm-Directly-pass-the-firwmare-using-bios-with-SNP.patch
  packages/by-name/kata/kata-runtime/0002-emulate-CPU-model-that-most-closely-matches-the-host.patch
  packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
  packages/by-name/kata/kata-runtime/0004-qemu-don-t-emit-scsi-parameter.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: no changelog

#843 containers.openssl: reduce size by 85%
  e2e/openssl/openssl_test.go
  internal/kuberesource/sets.go
  packages/containers.nix
Labels: no changelog
