Repository edgelesssys/contrast, pull requests merged in 2024-11, with the labels that each got.

#969 deps: update pinned rpm packages
  packages/by-name/kata/kata-image/package-index.json
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#962 just: use default platform for get-credentials
  .github/workflows/asciinema.yml
  .github/workflows/e2e.yml
  .github/workflows/release.yml
  justfile
Labels: no changelog

#955 packages/nixos: pin nvidia driver
  packages/nixos/gpu.nix
Labels: no changelog

#970 kata: 3.9.0 -> 3.10.1
  packages/by-name/kata/kata-runtime/0001-govmm-Directly-pass-the-firwmare-using-bios-with-SNP.patch
  packages/by-name/kata/kata-runtime/0002-emulate-CPU-model-that-most-closely-matches-the-host.patch
  packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
  packages/by-name/kata/kata-runtime/0004-genpolicy-enable-sysctl-checks.patch
  packages/by-name/kata/kata-runtime/0004-genpolicy-validate-create-sandbox-storages.patch
  packages/by-name/kata/kata-runtime/0005-genpolicy-read-bundle-id-from-rootfs.patch
  packages/by-name/kata/kata-runtime/0006-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
  packages/by-name/kata/kata-runtime/0007-genpolicy-settings-bump-OCI-version.patch
  packages/by-name/kata/kata-runtime/0008-genpolicy-settings-change-cpath-for-Nydus-guest-pull.patch
  packages/by-name/kata/kata-runtime/0009-genpolicy-allow-image_guest_pull.patch
  packages/by-name/kata/kata-runtime/0010-runtime-agent-mounts-Mount-configfs-into-the-contain.patch
  packages/by-name/kata/kata-runtime/0011-genpolicy-bump-oci-distribution-to-v0.12.0.patch
  packages/by-name/kata/kata-runtime/0012-genpolicy-support-mount-propagation-and-ro-mounts.patch
  packages/by-name/kata/kata-runtime/0013-tools-don-t-clean-build-root-when-generating-rootfs.patch
  packages/by-name/kata/kata-runtime/0014-kata-sys-util-remove-obsolete-cgroups-dependency.patch
  packages/by-name/kata/kata-runtime/0015-kata-agent-fixing-bug-of-unable-setting-hostname-cor.patch
  packages/by-name/kata/kata-runtime/0015-kata-sys-util-move-json-parsing-to-protocols-crate.patch
  packages/by-name/kata/kata-runtime/0016-agent-Correct-rustjail-device-filemode-permission-ty.patch
  packages/by-name/kata/kata-runtime/0016-protocols-only-build-RLimit-impls-on-Linux.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: changelog

#977 just: ensure peerpod vms are cleaned up on undeploy
  justfile
Labels: no changelog

#984 e2e/servicemesh: set hostname explicitly
  e2e/servicemesh/servicemesh_test.go
Labels: no changelog

#995 scripts: add publisher info for peer pods image
  packages/scripts.nix
Labels: no changelog

#1002 codeowners: remove Freax13
  .github/CODEOWNERS
Labels: no changelog

#989 packages.OVMF-SNP: patch missing git submodule
  packages/by-name/OVMF-SNP/package.nix
Labels: no changelog

#1010 coordinator: add log messages for handshake failures
  coordinator/internal/authority/credentials.go
Labels: no changelog

#1006 ci: prevent merge of PRs with do-not-merge label
  .github/workflows/require_label.yml
Labels: no changelog

#997 github: add issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: no changelog

#987 deps: update pinned rpm packages
  packages/by-name/kata/kata-image/package-index.json
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1016 go.work: update go version
  go.work
Labels: no changelog

#1014 flake: add comment to workaround renovate bug
  flake.nix
Labels: no changelog

#1009 e2e: show debug logs on error
  e2e/internal/contrasttest/contrasttest.go
Labels: no changelog

#985 e2e: improve log collection
  .github/workflows/e2e.yml
  .github/workflows/e2e_aks_runtime.yml
  packages/by-name/k8s-log-collector/package.nix
  packages/log-collector.yaml
  packages/scripts.nix
Labels: no changelog

#1007 e2e: default policy test
  e2e/internal/kubeclient/deploy.go
  e2e/policy/policy_test.go
Labels: no changelog

#1021 e2e: don't require e2e on unrelated PRs
  .github/workflows/e2e_openssl.yml
Labels: no changelog

#1022 packages/kata-debug-shell: init
  dev-docs/serial-console.md
  packages/kata-debug-shell.sh
Labels: no changelog

#1028 ci: descriptive names for tests
  .github/workflows/e2e_manual.yml
  .github/workflows/e2e_nightly.yml
  .github/workflows/e2e_on_pull_request.yml
  .github/workflows/e2e_service_mesh.yml
Labels: no changelog

#1025 docs: refactor gtag
  docs/docusaurus.config.js
  docs/package.json
  docs/static/gtagman.js
Labels: no changelog

#1029 packages/kata-debug-shell: fix templating
  packages/kata-debug-shell.sh
Labels: no changelog

#1027 attestation: log Validate errors
  internal/attestation/snp/validator.go
  internal/attestation/tdx/validator.go
Labels: no changelog

#1032 kata: remove rustc from agent closure
  packages/by-name/kata/kata-agent/package.nix
Labels: no changelog

#1031 e2e: fix policy test dependence on default policy test
  e2e/policy/policy_test.go
Labels: no changelog

#1033 cli: pass environment variables to genpolicy
  cli/genpolicy/genpolicy.go
  cli/genpolicy/genpolicy_test.go
Labels: bug fix

#996 kata-msft: support images with VOLUME directives
  e2e/regression/testdata/mongodb.yml
  e2e/regression/testdata/prometheus.yml
  e2e/regression/testdata/redis.yml
  packages/by-name/microsoft/genpolicy/0001-genpolicy-add-rules-and-types-for-volumeDevices.patch
  packages/by-name/microsoft/genpolicy/0002-genpolicy-add-ability-to-filter-for-runtimeClassName.patch
  packages/by-name/microsoft/genpolicy/0003-genpolicy-allow-specifying-layer-cache-file.patch
  packages/by-name/microsoft/genpolicy/0004-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
  packages/by-name/microsoft/genpolicy/0005-genpolicy-propagate-mount_options-for-empty-dirs.patch
  packages/by-name/microsoft/genpolicy/0006-genpolicy-support-HostToContainer-mount-propagation.patch
  packages/by-name/microsoft/genpolicy/0007-genpolicy-support-for-VOLUME-definition-in-container.patch
  packages/by-name/microsoft/genpolicy/genpolicy_msft_settings_coordinator.patch
  packages/by-name/microsoft/genpolicy/genpolicy_msft_settings_dev.patch
  packages/by-name/microsoft/genpolicy/package.nix
Labels: bug fix

#1039 codeowners: reduce ownership
  .github/CODEOWNERS
Labels: no changelog

#1034 nixos-img: disable patchelf on executable-marked OS image
  packages/by-name/buildVerityUKI/package.nix
  packages/by-name/kata/kata-image/package.nix
  packages/by-name/microsoft/kata-igvm/package.nix
  packages/by-name/microsoft/kata-image/package.nix
Labels: changelog
