Repository edgelesssys/contrast, pull requests merged in 2024-07, with the labels that each got.

#654 dev-docs: fix links in life-of-a-confidential-container.md
  dev-docs/aks/life-of-a-confidential-container.md
Labels: no changelog

#656 flake: add more packages to dev shell
  flake.nix
Labels: no changelog

#651 node-installer: support bare-metal platforms
  node-installer/internal/constants/configuration-qemu-tdx.toml
  node-installer/internal/constants/constants.go
  node-installer/node-installer.go
  node-installer/node-installer_test.go
  node-installer/testdata/expected-aks-clh-snp.toml
  node-installer/testdata/expected-bare-metal-qemu-tdx.toml
Labels: no changelog

#653 manifest: validate seed share owner pubkeys
  internal/manifest/manifest.go
Labels: no changelog

#655 ca: include SubjectKeyId and AuthorityKeyId in certificates
  e2e/openssl/openssl_test.go
  internal/ca/ca.go
  internal/ca/ca_test.go
Labels: bug fix, backport release/v0.7

#593 genpolicy: add flag for cache path
  cli/cmd/common.go
  cli/cmd/generate.go
  packages/by-name/microsoft/genpolicy/genpolicy_msft_cache_path.patch
  packages/by-name/microsoft/genpolicy/package.nix
Labels: no changelog

#658 ci: always copy label on backport
  .github/workflows/backport.yml
Labels: no changelog

#657 [release/v0.7] ca: include SubjectKeyId and AuthorityKeyId in certificates
  e2e/openssl/openssl_test.go
  internal/ca/ca.go
  internal/ca/ca_test.go
Labels: bug fix

#662 docs: fix outdated service mesh annotations
  docs/docs/deployment.md
  docs/versioned_docs/version-0.7/deployment.md
Labels: no changelog

#663 packages: replace deprecates `sha256` with `hash`
  packages/by-name/kata/kata-kernel-uvm/package.nix
  packages/by-name/kata/runtime-class-files/package.nix
  packages/by-name/microsoft/genpolicy/package.nix
Labels: no changelog

#661 docs: use --reference-values aks flag on generate
  docs/docs/deployment.md
  docs/docs/examples/emojivoto.md
Labels: no changelog

#664 ci: unify workflow naming
  .github/workflows/e2e_regression.yml
  .github/workflows/e2e_runtime-reproducibility.yml
Labels: no changelog

#667 microsoft.genpolicy: drop revert tarindex symlink handling patch
  packages/by-name/microsoft/genpolicy/genpolicy_msft_revert_special_symlink_names.patch
  packages/by-name/microsoft/genpolicy/package.nix
Labels: bug fix, backport release/v0.7

#669 [release/v0.7] microsoft.genpolicy: drop revert tarindex symlink handling patch
  packages/by-name/microsoft/genpolicy/genpolicy_msft_revert_special_symlink_names.patch
  packages/by-name/microsoft/genpolicy/package.nix
Labels: bug fix

#674 scripts: add get-azure-node-image-version
  packages/scripts.nix
Labels: no changelog

#670 generate: rename --workload-owner-key to --add-workload-owner-key
  cli/cmd/generate.go
Labels: breaking change

#668 just: refactor e2e target, use undeploy target for e2e
  justfile
Labels: no changelog

#650 generate: check for existing public key in manifest
  cli/cmd/generate.go
Labels: no changelog

#673 packages/contrast{,-releases}: install shell completions
  packages/by-name/contrast/package.nix
  packages/contrast-releases.nix
Labels: no changelog

#675 docs: remove asciinema widget
  docs/package.json
  docs/screencast/README.md
  docs/screencast/window-frame.svg
  docs/src/components/AsciinemaWidget/index.js
  docs/src/theme/MDXComponents.js
  docs/yarn.lock
  packages/by-name/contrast-docs/package.nix
Labels: no changelog

#677 docs: update concept graphic
  docs/static/img/concept.svg
Labels: no changelog

#680 treefmt: switch from nixpkgs-fmt to nixfmt
  flake.nix
  overlays/nixpkgs.nix
  packages/by-name/buildGoTest/package.nix
  packages/by-name/cli-release/package.nix
  packages/by-name/contrast-docs/package.nix
  packages/by-name/contrast-node-installer/package.nix
  packages/by-name/contrast/package.nix
  packages/by-name/igvm-signing-keygen/package.nix
  packages/by-name/igvmmeasure/package.nix
  packages/by-name/kata/contrast-node-installer-image/package.nix
  packages/by-name/kata/genpolicy/package.nix
  packages/by-name/kata/kata-agent/package.nix
  packages/by-name/kata/kata-image/package.nix
  packages/by-name/kata/kata-kernel-uvm/package.nix
  packages/by-name/kata/kata-runtime/package.nix
  packages/by-name/kata/runtime-class-files/package.nix
  packages/by-name/microsoft/cloud-hypervisor/package.nix
  packages/by-name/microsoft/contrast-node-installer-image/package.nix
  packages/by-name/microsoft/genpolicy/package.nix
  packages/by-name/microsoft/kata-agent/package.nix
  packages/by-name/microsoft/kata-igvm/package.nix
  packages/by-name/microsoft/kata-image/package.nix
  packages/by-name/microsoft/kata-kernel-uvm/package.nix
  packages/by-name/microsoft/kata-runtime/package.nix
  packages/by-name/microsoft/runtime-class-files/package.nix
  packages/by-name/ociImageConfig/package.nix
  packages/by-name/ociImageLayout/package.nix
  packages/by-name/ociImageManifest/package.nix
  packages/by-name/ociLayerTar/package.nix
  packages/by-name/rpm-pin-vendor/package.nix
  packages/by-name/service-mesh/package.nix
  packages/containers.nix
  packages/contrast-releases.nix
  packages/scripts.nix
  treefmt.nix
Labels: no changelog

#682 git: add formatting commits to blame ignore
  .git-blame-ignore-revs
Labels: no changelog

#684 kuberesource: fix image URL typo
  internal/kuberesource/parts.go
Labels: no changelog

#683 node-installer: use full OVMF image on bare-metal TDX
  node-installer/internal/constants/constants.go
  packages/by-name/kata/contrast-node-installer-image/package.nix
  packages/by-name/kata/runtime-class-files/package.nix
Labels: no changelog

#685 packages: package bare-metal kata-runtime tool
  packages/by-name/kata/contrast-node-installer-image/package.nix
  packages/by-name/kata/kata-runtime/package.nix
  packages/by-name/kata/runtime-class-files/package.nix
  packages/default.nix
Labels: no changelog

#687 deps: update pinned rpm packages
  packages/by-name/kata/kata-image/package-index.json
Labels: dependencies

#690 issuer: don't open sev-guest device
  internal/attestation/snp/issuer.go
Labels: no changelog

#689 validator: explictly set trust roots
  internal/attestation/snp/Genoa.pem
  internal/attestation/snp/Milan.pem
  internal/attestation/snp/validator.go
  internal/attestation/snp/validator_test.go
  packages/by-name/contrast/package.nix
Labels: no changelog

#691 kata: add patches for bare metal SNP
  packages/by-name/kata/genpolicy/package.nix
  packages/by-name/kata/kata-runtime/0001-govmm-Directly-pass-the-firwmare-using-bios-with-SNP.patch
  packages/by-name/kata/kata-runtime/0002-emulate-CPU-model-that-most-closely-matches-the-host.patch
  packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: no changelog

#686 cli: use platform string for reference-values flag
  cli/cmd/generate.go
  docs/docs/deployment.md
  docs/docs/examples/emojivoto.md
  e2e/genpolicy/genpolicy_test.go
  e2e/getdents/getdents_test.go
  e2e/internal/contrasttest/contrasttest.go
  justfile
  node-installer/platforms/platforms.go
Labels: no changelog

#694 microsoft.genpolicy: use git format-patch for patches
  packages/by-name/microsoft/genpolicy/0001-genpolicy-add-rules-and-types-for-volumeDevices.patch
  packages/by-name/microsoft/genpolicy/0002-genpolicy-add-ability-to-filter-for-runtimeClassName.patch
  packages/by-name/microsoft/genpolicy/0003-genpolicy-allow-specifying-layer-cache-file.patch
  packages/by-name/microsoft/genpolicy/package.nix
Labels: no changelog

#693 scripts.extract-policies: fix and improve
  packages/scripts.nix
Labels: no changelog

#678 cli: print AKS reference values with the version
  cli/main.go
Labels: no changelog

#701 e2e: log debug info on test failure
  e2e/internal/contrasttest/contrasttest.go
  e2e/internal/kubeclient/kubeclient.go
Labels: no changelog

#703 snp: don't test properties that are not guaranteed
  internal/attestation/snp/cached_client_test.go
Labels: no changelog

#706 e2e/release: add missing generate flag
  e2e/release/release_test.go
Labels: no changelog

#708 generate: mark `--reference-values` flag as required
  cli/cmd/generate.go
Labels: no changelog

#709 cli: change key file permissions to 0600
  cli/cmd/generate.go
Labels: bug fix

#710 ci: fix missing "current version" in commit message from `bump_version` action
  .github/actions/bump_version/action.yml
Labels: no changelog

#702 nix: build static QEMU
  packages/by-name/kata/runtime-class-files/package.nix
  packages/by-name/qemu-static/0001-avoid-duplicate-definitions.patch
  packages/by-name/qemu-static/0001-fix-static-build.patch
  packages/by-name/qemu-static/0002-add-options-for-library-paths.patch
  packages/by-name/qemu-static/package.nix
  packages/default.nix
Labels: no changelog

#711 ci: fix typo
  .github/workflows/static.yml
Labels: no changelog

#672 ci: add an e2e test for policy changes
  .github/workflows/e2e_policy.yml
  e2e/policy/policy_test.go
  go.mod
  packages/by-name/contrast/package.nix
Labels: no changelog

#712 nix: add support for building QEMU with SEV-SNP patches
  packages/by-name/qemu-static/package.nix
Labels: no changelog

#713 nix: lib.optional doesn't take a list
  packages/by-name/microsoft/cloud-hypervisor/package.nix
Labels: no changelog

#720 dev-docs: document AKS release flow
  dev-docs/aks/node-image.md
Labels: no changelog

#722 meshapi: follow best practice for metric names
  coordinator/meshapi.go
  docs/docs/architecture/observability.md
  e2e/policy/policy_test.go
Labels: breaking change

#724 deps: update pinned rpm packages
  packages/by-name/kata/kata-image/package-index.json
Labels: dependencies

#725 scripts/destroy-coco-aks: delete resource group if not in ci
  packages/destroy-coco-aks.sh
Labels: no changelog

#726 e2e: fix reproducibility test, don't fail fast
  .github/workflows/e2e_runtime-reproducibility.yml
Labels: no changelog

#727 dev-docs: document microsoft containerd fork
  dev-docs/aks/node-image.md
Labels: no changelog

#732 coordinator: use random key for intermediate CA
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/userapi.go
  coordinator/internal/seedengine/seedengine.go
  coordinator/internal/seedengine/seedengine_test.go
  docs/docs/deployment.md
  e2e/openssl/openssl_test.go
Labels: bug fix, backport release/v0.8

#733 [release/v0.8] coordinator: use random key for intermediate CA
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/userapi.go
  coordinator/internal/seedengine/seedengine.go
  coordinator/internal/seedengine/seedengine_test.go
  docs/docs/deployment.md
  e2e/openssl/openssl_test.go
Labels: bug fix

#734 docs: backport recovery warning to v0.8
  docs/versioned_docs/version-0.8/deployment.md
Labels: no changelog

#737 docs: update persistent volume limitation
  docs/docs/features-limitations.md
  docs/versioned_docs/version-0.8/features-limitations.md
Labels: documentation

#739 renovate: ignore node-installer
  renovate.json5
Labels: no changelog

#742 dev-docs: document patching conventions
  dev-docs/patches.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#748 ci: always show full build output
  .github/workflows/e2e_openssl.yml
  .github/workflows/e2e_policy.yml
  .github/workflows/e2e_regression.yml
  .github/workflows/e2e_servicemesh.yml
  .github/workflows/release.yml
Labels: no changelog

#749 atls: try to attest with all validators
  coordinator/main.go
  initializer/main.go
  internal/atls/atls.go
  internal/atls/atls_test.go
  internal/atls/issuer.go
  internal/attestation/oid.go
Labels: no changelog

#750 just: add get-credentials-tdxbm
  justfile
Labels: no changelog

#741 kata: 3.6.0 -> 3.7.0
  packages/by-name/kata/kata-agent/package.nix
  packages/by-name/kata/kata-kernel-uvm/package.nix
  packages/by-name/kata/kata-runtime/0001-govmm-Directly-pass-the-firwmare-using-bios-with-SNP.patch
  packages/by-name/kata/kata-runtime/0002-emulate-CPU-model-that-most-closely-matches-the-host.patch
  packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: no changelog

#757 just: add get-credentials-snpbm
  justfile
Labels: no changelog

#760 vale: enable Microsoft.FirstPerson and Microsoft.Terms
  .vale.ini
  docs/docs/architecture/attestation.md
  docs/docs/getting-started/cluster-setup.md
  docs/docs/troubleshooting.md
  docs/versioned_docs/version-0.5/getting-started/cluster-setup.md
  docs/versioned_docs/version-0.6/architecture/attestation.md
  docs/versioned_docs/version-0.6/getting-started/cluster-setup.md
  docs/versioned_docs/version-0.7/architecture/attestation.md
  docs/versioned_docs/version-0.7/getting-started/cluster-setup.md
  docs/versioned_docs/version-0.8/architecture/attestation.md
  docs/versioned_docs/version-0.8/getting-started/cluster-setup.md
  docs/versioned_docs/version-0.8/troubleshooting.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#762 ci: don't trigger e2e on unrelated changes
  .github/workflows/e2e_openssl.yml
  .github/workflows/e2e_policy.yml
  .github/workflows/e2e_servicemesh.yml
Labels: no changelog

#763 cli: always write the coordinator policy hash file
  cli/cmd/policies.go
Labels: bug fix

#766 deps: update pinned rpm packages
  packages/by-name/kata/kata-image/package-index.json
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#774 cli-release: embed reference values
  packages/by-name/cli-release/package.nix
  packages/by-name/contrast/package.nix
Labels: no changelog

#775 Share Go module between node-installer and contrast
  cli/cmd/generate.go
  coordinator/internal/authority/authority_test.go
  coordinator/internal/authority/userapi_test.go
  e2e/genpolicy/genpolicy_test.go
  e2e/getdents/getdents_test.go
  e2e/internal/contrasttest/contrasttest.go
  e2e/openssl/openssl_test.go
  e2e/policy/policy_test.go
  e2e/servicemesh/servicemesh_test.go
  go.mod
  go.sum
  go.work
  internal/kuberesource/parts.go
  internal/kuberesource/resourcegen/main.go
  internal/kuberesource/sets.go
  internal/manifest/constants.go
  internal/manifest/manifest.go
  internal/manifest/manifest_test.go
  internal/platforms/platforms.go
  node-installer/go.mod
  node-installer/go.sum
  nodeinstaller/README.md
  nodeinstaller/internal/asset/fetcher.go
  nodeinstaller/internal/asset/fetcher_test.go
  nodeinstaller/internal/asset/file.go
  nodeinstaller/internal/asset/http.go
  nodeinstaller/internal/config/config.go
  nodeinstaller/internal/config/config_test.go
  nodeinstaller/internal/config/containerd.go
  nodeinstaller/internal/config/kata_runtime.go
  nodeinstaller/internal/constants/configuration-clh-snp.toml
  nodeinstaller/internal/constants/configuration-qemu-snp.toml
  nodeinstaller/internal/constants/configuration-qemu-tdx.toml
  nodeinstaller/internal/constants/constants.go
  nodeinstaller/internal/constants/containerd-config.toml
  nodeinstaller/internal/fileop/copy_general.go
  nodeinstaller/internal/fileop/copy_linux.go
  nodeinstaller/internal/fileop/fileop.go
  nodeinstaller/internal/fileop/fileop_test.go
  nodeinstaller/node-installer.go
  nodeinstaller/node-installer_test.go
  nodeinstaller/testdata/expected-aks-clh-snp.toml
  nodeinstaller/testdata/expected-bare-metal-qemu-snp.toml
  nodeinstaller/testdata/expected-bare-metal-qemu-snp.toml.tmpl
  nodeinstaller/testdata/expected-bare-metal-qemu-tdx.toml
  nodeinstaller/testdata/expected-bare-metal-qemu-tdx.toml.tmpl
  nodeinstaller/testdata/input-bare-metal-qemu-snp.toml.tmpl
  nodeinstaller/testdata/input-bare-metal-qemu-tdx.toml.tmpl
  packages/by-name/contrast-node-installer/package.nix
  packages/by-name/contrast/package.nix
  packages/by-name/kata/contrast-node-installer-image/package.nix
  packages/by-name/microsoft/contrast-node-installer-image/package.nix
  packages/scripts.nix
Labels: no changelog
