Repository edgelesssys/contrast, pull requests merged in 2024-06, with the labels that each got.

#515 docs: better error message when forgetting to set variables
  docs/docs/getting-started/cluster-setup.md
  docs/versioned_docs/version-0.6/getting-started/cluster-setup.md
Labels: documentation

#519 release: fix coordinator policy hash
  .github/workflows/release.yml
  e2e/release/release_test.go
Labels: no changelog

#513 Rename "limitations" section
  README.md
  docs/docs/deployment.md
  docs/docs/features-limitations.md
  docs/sidebars.js
Labels: no changelog

#523 seedengine: move into coordinator
  coordinator/internal/seedengine/seedengine.go
  coordinator/internal/seedengine/seedengine_test.go
Labels: no changelog

#528 deps/go_1_22: 1.22.3 -> 1.22.4
  overlays/nixpkgs.nix
Labels: dependencies

#522 coordinator: implement history with fs store backend
  coordinator/history/fsstore.go
  coordinator/history/history.go
  coordinator/history/history_test.go
Labels: no changelog

#499 ci: improvements for external contributors
  .github/workflows/docs_publish.yml
  .github/workflows/static.yml
Labels: no changelog

#504 genpolicy: add patch to filter for runtime class
  cli/cmd/generate.go
  packages/by-name/genpolicy-msft/genpolicy_msft_runtime_class_filter.patch
  packages/by-name/genpolicy-msft/package.nix
Labels: no changelog

#488 ci: create and update a `versions.json` file
  .github/workflows/release.yml
  packages/contrast-releases.json
  packages/scripts.nix
  packages/update-contrast-releases.sh
Labels: no changelog

#520 coordinator: don't share CA instance with gRPC servers
  coordinator/internal/authority/authority.go
  coordinator/main.go
  coordinator/meshapi.go
  coordinator/userapi.go
  coordinator/userapi_test.go
  initializer/main.go
  internal/meshapi/meshapi.pb.go
  internal/meshapi/meshapi.proto
Labels: no changelog

#536 e2e: correctly report unexpected watch events
  e2e/internal/kubeclient/deploy.go
Labels: no changelog

#521 coordinator: rotate certs in authority
  coordinator/internal/authority/authority.go
  coordinator/main.go
  coordinator/userapi_test.go
  internal/ca/ca.go
  internal/ca/ca_test.go
Labels: no changelog

#539 cli: check yaml for unknown fields
  internal/kuberesource/reader.go
  internal/kuberesource/reader_writer_test.go
Labels: no changelog

#541 nix: make `just demodir` to a nix devshell
  flake.nix
  justfile
  packages/contrast-releases.nix
  packages/default.nix
Labels: no changelog

#545 packages/scripts.fetch-latest-contrast: remove
  packages/scripts.nix
Labels: no changelog

#546 just: undeploy on demodir
  justfile
Labels: no changelog

#544 setLoop: wait 180s for the coordinator
  cli/cmd/set.go
Labels: bug fix

#550 ci: add workflow to update rpm package pins
  .github/workflows/rpm_updates.yml
Labels: no changelog

#549 deps: update pinned rpm packages
  packages/by-name/kata-image/package-index.json
Labels: dependencies

#552 docs: tidy
  docs/docs/basics/confidential-containers.md
  docs/docs/basics/security-benefits.md
  docs/docs/components/index.md
  docs/docs/components/service-mesh.md
  docs/docs/deployment.md
  docs/docs/examples/emojivoto.md
  docs/docs/getting-started/cluster-setup.md
Labels: no changelog

#548 docs: manual initializer setup
  docs/docs/deployment.md
Labels: no changelog

#547 cli: error checking for struct fields
  cli/cmd/generate.go
  internal/kuberesource/mutators.go
Labels: no changelog

#558 packages/scripts: add accidentally removed input
  packages/scripts.nix
Labels: no changelog

#560 flake: fix demodir file permissions
  flake.nix
Labels: no changelog

#563 docs: fix search
  docs/package.json
  docs/yarn.lock
  packages/by-name/contrast-docs/package.nix
Labels: no changelog

#559 release: patch latest references in versioned docs
  .github/workflows/release.yml
  packages/scripts.nix
Labels: no changelog

#567 e2e: easier fifo recreation for CI cluster
  e2e/internal/contrasttest/contrasttest.go
  packages/scripts.nix
Labels: no changelog

#569 packages/igvm-tooling: remove
  packages/by-name/igvm-tooling/package.nix
Labels: no changelog

#566 resourcegen: cleanup emojivoto env variables
  internal/kuberesource/sets.go
Labels: no changelog

#575 packages: update kata-igvm to microsoft upstream
  packages/by-name/microsoft/genpolicy/package.nix
  packages/by-name/microsoft/kata-igvm/package.nix
Labels: no changelog

#573 resourcegen: add startup probe to service mesh
  internal/kuberesource/parts.go
Labels: no changelog

#576 docs: update service mesh image reference
  docs/docs/components/service-mesh.md
  docs/versioned_docs/version-0.7/components/service-mesh.md
Labels: no changelog

#571 docs: add troubleshooting page
  docs/docs/troubleshooting.md
  docs/sidebars.js
Labels: documentation

#551 coordinator: use history in authority
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/authority_test.go
  coordinator/main.go
  coordinator/userapi.go
  coordinator/userapi_test.go
Labels: no changelog

#580 packages/contrast-releases: fix v0.7.0 and update workflow on release
  .github/workflows/release.yml
  packages/contrast-releases.json
Labels: no changelog

#570 recovery: add server and recover authority
  coordinator/internal/authority/authority.go
  coordinator/main.go
  coordinator/recoveryapi.go
  internal/recoveryapi/recoveryapi.go
  internal/recoveryapi/recoveryapi.pb.go
  internal/recoveryapi/recoveryapi.proto
  internal/recoveryapi/recoveryapi_grpc.pb.go
Labels: no changelog

#582 [release/v0.7] release: fix update of contrast-releases.json
  .github/workflows/release.yml
Labels: no changelog

#581 packages: package cloud-hypervisor-cvm
  packages/by-name/microsoft/cloud-hypervisor/package.nix
  packages/by-name/runtime-class-files/package.nix
  packages/default.nix
Labels: no changelog

#589 scripts/create-coco-aks: switch default region to germany west central
  packages/create-coco-aks.sh
Labels: no changelog

#585 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#586 docs: update graphics
  README.md
  docs/docs/_media/components.svg
  docs/docs/_media/personas.svg
  docs/docs/intro.md
  docs/static/img/concept.svg
  docs/versioned_docs/version-0.7/_media/components.svg
  docs/versioned_docs/version-0.7/_media/personas.svg
  docs/versioned_docs/version-0.7/intro.md
Labels: no changelog

#591 packages: package kata-kernel
  packages/by-name/kata/kata-kernel-uvm/kernel.config
  packages/by-name/kata/kata-kernel-uvm/package.nix
Labels: no changelog

#592 e2e: cleanup when test is cancelled
  .github/workflows/e2e_getdents.yml
  .github/workflows/e2e_openssl.yml
  .github/workflows/e2e_servicemesh.yml
  e2e/getdents/getdents_test.go
  e2e/internal/contrasttest/contrasttest.go
  e2e/openssl/openssl_test.go
  e2e/servicemesh/servicemesh_test.go
Labels: no changelog

#597 cli: fix autocomplete
  cli/main.go
Labels: bug fix

#601 just: add e2e target
  justfile
Labels: no changelog

#590 manifest: add utilities for encrypted SeedShares
  internal/manifest/crypto.go
  internal/manifest/crypto_test.go
Labels: no changelog

#604 coordinator: enable returning seed to user
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/authority_test.go
  coordinator/internal/authority/recoveryapi.go
  coordinator/internal/authority/userapi.go
  coordinator/internal/authority/userapi_test.go
Labels: no changelog

#608 cli: use manifest reference values for attestation
  cli/cmd/common.go
  cli/cmd/set.go
  cli/cmd/verify.go
  coordinator/internal/authority/authority.go
  e2e/internal/contrasttest/contrasttest.go
  internal/manifest/manifest.go
  justfile
Labels: changelog

#617 docs: add bare metal availability
  docs/versioned_docs/version-0.7/features-limitations.md
Labels: no changelog

#619 genpolicy-msft: revert problematic tarindex commit
  packages/by-name/microsoft/genpolicy/genpolicy_msft_revert_special_symlink_names.patch
  packages/by-name/microsoft/genpolicy/genpolicy_msft_runtime_class_filter.patch
  packages/by-name/microsoft/genpolicy/package.nix
Labels: bug fix, backport release/v0.7

#621 [release/v0.7]: genpolicy-msft: revert problematic tarindex commit
  packages/by-name/microsoft/genpolicy/genpolicy_msft_revert_special_symlink_names.patch
  packages/by-name/microsoft/genpolicy/genpolicy_msft_runtime_class_filter.patch
  packages/by-name/microsoft/genpolicy/package.nix
Labels: bug fix

#623 packages/runtime-class-files: use version of kata-igvm
  packages/by-name/contrast-node-installer-image/package.nix
  packages/by-name/runtime-class-files/package.nix
Labels: no changelog

#628 release: update contrast-releases.json on main branch; minor improvements
  .github/workflows/release.yml
Labels: no changelog

#631 scripts: add tools to debug policy failures
  packages/scripts.nix
Labels: no changelog

#626 cli: remove runtime subcommand
  cli/cmd/common.go
  cli/cmd/runtime.go
  cli/main.go
Labels: breaking change

#625 docs: verify command takes in manifest file
  docs/docs/deployment.md
  docs/docs/examples/emojivoto.md
Labels: documentation

#630 manifest: validate manifest fields
  cli/cmd/generate.go
  cli/cmd/set.go
  cli/cmd/verify.go
  internal/manifest/manifest.go
  internal/manifest/manifest_test.go
Labels: no changelog

#633 generate: translate genpolicy logs, show warnings
  cli/cmd/generate.go
  cli/cmd/generate_test.go
Labels: changelog

#638 node-installer: add platforms
  node-installer/platforms/platforms.go
Labels: no changelog

#639 recoveryapi: cleanup and remove
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/recoveryapi.go
  coordinator/internal/authority/recoveryapi_test.go
  coordinator/internal/authority/userapi.go
  coordinator/internal/authority/userapi_test.go
  coordinator/main.go
  internal/recoveryapi/recoveryapi.go
  internal/recoveryapi/recoveryapi.pb.go
  internal/recoveryapi/recoveryapi.proto
  internal/recoveryapi/recoveryapi_grpc.pb.go
  internal/userapi/userapi.pb.go
  internal/userapi/userapi.proto
  internal/userapi/userapi_grpc.pb.go
Labels: no changelog

#642 cmd/recover: fix recoveryapi -> userapi
  cli/cmd/recover.go
Labels: no changelog

#615 verify: verify active manifest at Coordinator
  cli/cmd/generate.go
  cli/cmd/verify.go
Labels: changelog

#618 cli: derive runtime class name from launch digest
  cli/cmd/common.go
  cli/cmd/generate.go
  cli/main.go
  internal/manifest/constants.go
  packages/by-name/contrast/package.nix
Labels: no changelog

#637 dev-docs: overview of CoCo AKS and support policy
  dev-docs/aks/README.md
Labels: no changelog

#640 release: publish emojivoto as yml instead of zip
  .github/workflows/release.yml
  docs/docs/examples/emojivoto.md
  e2e/release/release_test.go
  packages/contrast-releases.nix
  packages/update-contrast-releases.sh
Labels: no changelog

#614 docs: extend troubleshooting guide
  docs/docs/troubleshooting.md
Labels: documentation

#629 ci: add reproducibility test for runtime components
  .github/workflows/runtime-reproducibility.yml
Labels: no changelog

#649 ci: improve debug logging for e2e tests
  cli/cmd/generate.go
  e2e/internal/contrasttest/contrasttest.go
Labels: no changelog

#645 dev-docs: life of a confidential container
  dev-docs/aks/life-of-a-confidential-container.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog
