Repository edgelesssys/contrast, pull requests merged in 2024-10, with the labels that each got.

#902 atls: explain need for NextProtos
  internal/atls/atls.go
Labels: no changelog

#903 infra: add terraform lock file
  .gitignore
  infra/azure-peerpods/.terraform.lock.hcl
Labels: no changelog

#906 renovate: group terraform updates
  renovate.json5
Labels: no changelog

#888 e2e: add ability to wait for different conditions in `kubeclient.WaitFor`
  e2e/genpolicy/genpolicy_test.go
  e2e/getdents/getdents_test.go
  e2e/internal/contrasttest/contrasttest.go
  e2e/internal/kubeclient/deploy.go
  e2e/internal/kubeclient/kubeclient.go
  e2e/openssl/openssl_test.go
  e2e/policy/policy_test.go
  e2e/regression/regression_test.go
  e2e/release/release_test.go
  e2e/servicemesh/servicemesh_test.go
  e2e/volumestatefulset/volumestatefulset_test.go
  e2e/workloadsecret/workloadsecret_test.go
Labels: no changelog

#895 ci: send notifications to teams channel
  .github/actions/post_to_teams/action.yml
  .github/workflows/e2e_regression.yml
  .github/workflows/e2e_runtime-reproducibility.yml
  .github/workflows/rpm_updates.yml
Labels: no changelog

#909 docs: add security considerations
  docs/docs/architecture/security-considerations.md
  docs/docs/deployment.md
  docs/sidebars.js
Labels: documentation

#914 codeowners: update
  .github/CODEOWNERS
Labels: no changelog

#917 scripts: fix get-credentials
  packages/scripts.nix
Labels: no changelog

#911 e2e: apply backoff after failed port-forwarding attempt
  e2e/internal/kubeclient/portforward.go
Labels: no changelog

#908 e2e: test verify on coordinator with different policy
  e2e/internal/contrasttest/contrasttest.go
  e2e/policy/policy_test.go
Labels: no changelog

#925 ci: use card template for teams post
  .github/actions/post_to_teams/action.yml
  .github/actions/post_to_teams/teams_card_template.json
  .github/workflows/e2e.yaml
  .github/workflows/e2e_runtime-reproducibility.yml
  .github/workflows/rpm_updates.yml
Labels: no changelog

#929 justfile: bump version for snp kubeconfig secret
  justfile
Labels: no changelog

#934 e2e/policy: ensure that modified policy hash is valid hex
  e2e/policy/policy_test.go
Labels: no changelog

#930 sets: add StartupProbe to vss deployment
  internal/kuberesource/sets.go
Labels: no changelog

#936 image-podvm: drop assertion supression
  packages/nixos/image.nix
Labels: no changelog

#928 deps: update pinned rpm packages
  packages/by-name/kata/kata-image/package-index.json
Labels: dependencies

#933 tools: periodically clean up bare-metal servers
  packages/cleanup-bm.sh
  packages/containers.nix
  packages/scripts.nix
  tools/bm-maintenance/deployment_tdx_snp.yml
Labels: no changelog

#948 node-installer: remove resource limits
  internal/kuberesource/parts.go
Labels: no changelog

#942 deps: update pinned rpm packages
  packages/by-name/kata/kata-image/package-index.json
Labels: dependencies

#951 docs/troubleshooting: fix typo
  docs/docs/troubleshooting.md
Labels: no changelog

#949 just: configure platform from jusfile.env file
  justfile
Labels: no changelog

#954 packages/contrast: prefix version string with v
  packages/by-name/contrast/package.nix
Labels: no changelog

#945 infra: better default values
  infra/azure-peerpods/main.tf
  infra/azure-peerpods/vars.tf
Labels: no changelog

#939 e2e: add a test for checking AKS upstream
  .github/workflows/e2e_aks_runtime.yml
  e2e/aks-runtime/aks_runtime_test.go
  e2e/internal/az/aks.go
  e2e/internal/az/confcom.go
  e2e/internal/contrasttest/contrasttest.go
  flake.nix
  overlays/nixpkgs.nix
  packages/by-name/contrast/package.nix
Labels: no changelog

#966 kata.kata-runtime: cherry pick 3.10.1 bug fixes
  packages/by-name/kata/kata-runtime/0001-govmm-Directly-pass-the-firwmare-using-bios-with-SNP.patch
  packages/by-name/kata/kata-runtime/0002-emulate-CPU-model-that-most-closely-matches-the-host.patch
  packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
  packages/by-name/kata/kata-runtime/0004-genpolicy-validate-create-sandbox-storages.patch
  packages/by-name/kata/kata-runtime/0005-genpolicy-enable-sysctl-checks.patch
  packages/by-name/kata/kata-runtime/0006-genpolicy-read-bundle-id-from-rootfs.patch
  packages/by-name/kata/kata-runtime/0007-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
  packages/by-name/kata/kata-runtime/0008-genpolicy-settings-bump-OCI-version.patch
  packages/by-name/kata/kata-runtime/0009-genpolicy-settings-change-cpath-for-Nydus-guest-pull.patch
  packages/by-name/kata/kata-runtime/0010-genpolicy-allow-image_guest_pull.patch
  packages/by-name/kata/kata-runtime/0011-runtime-agent-mounts-Mount-configfs-into-the-contain.patch
  packages/by-name/kata/kata-runtime/0012-genpolicy-bump-oci-distribution-to-v0.12.0.patch
  packages/by-name/kata/kata-runtime/0013-genpolicy-support-mount-propagation-and-ro-mounts.patch
  packages/by-name/kata/kata-runtime/0014-tools-don-t-clean-build-root-when-generating-rootfs.patch
  packages/by-name/kata/kata-runtime/0015-kata-agent-fixing-bug-of-unable-setting-hostname-cor.patch
  packages/by-name/kata/kata-runtime/0016-agent-Correct-rustjail-device-filemode-permission-ty.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: changelog

#965 overlay: remove azure-cli with confcom extension
  flake.nix
  overlays/nixpkgs.nix
Labels: no changelog

#960 e2e: fix runtime reproducibility test and also check `kata.contrast-node-installer-image`
  .github/workflows/e2e_runtime-reproducibility.yml
Labels: no changelog
