Repository edgelesssys/contrast, pull requests merged in 2025-01, with the labels that each got.

#1095 attestation: add name to Validator as unique identifier
  coordinator/internal/authority/credentials.go
  internal/atls/atls.go
  internal/attestation/snp/validator.go
  internal/attestation/tdx/validator.go
  sdk/common.go
Labels: no changelog

#1114 ci: fix platform case statements
  .github/workflows/e2e_manual.yml
  packages/scripts.nix
Labels: no changelog, backport release/v1.2

#1118 ci/release: allow setting main ref for testing
  .github/workflows/release.yml
Labels: no changelog, backport release/v1.2

#1119 [release/v1.2] ci/release: allow setting main ref for testing
  .github/workflows/release.yml
Labels: no changelog

#1116 [release/v1.2] ci: fix platform case statements
  .github/workflows/e2e_manual.yml
  packages/scripts.nix
Labels: no changelog

#1123 just: enable deploying custom resources
  .gitignore
  justfile
Labels: no changelog

#1121 cli: remove unused skip initializer variable
  cli/cmd/generate.go
Labels: no changelog

#1092 nixos: minimize GPU image
  packages/nixos/gpu.nix
Labels: no changelog

#1128 microsoft.genpolicy: 3.2.0.azl1.genpolicy0 -> 3.2.0.azl1.genpolicy1
  packages/by-name/microsoft/genpolicy/0001-genpolicy-add-rules-and-types-for-volumeDevices.patch
  packages/by-name/microsoft/genpolicy/0002-genpolicy-add-ability-to-filter-for-runtimeClassName.patch
  packages/by-name/microsoft/genpolicy/0004-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
  packages/by-name/microsoft/genpolicy/0007-genpolicy-support-for-VOLUME-definition-in-container.patch
  packages/by-name/microsoft/genpolicy/package.nix
  packages/by-name/microsoft/kata-igvm/package.nix
Labels: changelog

#1129 generate: support cronjobs
  cli/cmd/policies.go
Labels: feature

#1122 generate: add flag to skip service mesh injection
  cli/cmd/generate.go
Labels: feature

#1065 rfc: add platform support RFC
  rfc/008-platform-support.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#1115 e2e: use real reference values on bare-metal runners
  e2e/internal/contrasttest/contrasttest.go
Labels: no changelog

#1139 microsoft.genpolicy: support volume mounting
  packages/by-name/microsoft/genpolicy/0010-genpolicy-support-mount-propagation-and-ro-mounts.patch
  packages/by-name/microsoft/genpolicy/package.nix
Labels: no changelog

#1142 service-mesh: test readiness with exec probe
  internal/kuberesource/parts.go
  internal/kuberesource/wrappers.go
  packages/containers.nix
  service-mesh/main.go
Labels: bug fix, backport release/v1.2

#1154 e2e/release: increase timeout for generate
  e2e/release/release_test.go
Labels: no changelog

#1155 contrast-releases: gpu assets postponed to v1.4.0
  packages/contrast-releases.nix
Labels: no changelog

#1146 dev-docs: add tracing doc
  dev-docs/coco/tracing.md
Labels: no changelog

#1165 packages.tdx-tools: noble-24.04 -> 3.1
  packages/by-name/tdx-tools/package.nix
Labels: dependencies

#1138 microsoft.cloud-hypervisor: 38.0.72 -> 38.0.72.3
  packages/by-name/microsoft/cloud-hypervisor/package.nix
Labels: changelog

#1159 ci: simplify if statements in workflows
  .github/workflows/e2e.yml
  .github/workflows/e2e_aks_runtime.yml
  .github/workflows/e2e_runtime-reproducibility.yml
  .github/workflows/release.yml
  .github/workflows/require_label.yml
  .github/workflows/rpm_updates.yml
Labels: no changelog

#1157 initializer: add Cobra for subcommands
  initializer/main.go
Labels: changelog

#1170 treewide: CGO_ENABLED -> env.CGO_ENABLED
  packages/by-name/cloud-api-adaptor/package.nix
  packages/by-name/contrast/package.nix
  packages/by-name/microsoft/kata-runtime/package.nix
  packages/by-name/nydus-pull/package.nix
  packages/by-name/nydus-snapshotter/package.nix
  packages/by-name/service-mesh/package.nix
  packages/by-name/tdx-measure/package.nix
Labels: no changelog

#1148 kuberesource: serve images from edgelesssys org
  internal/kuberesource/sets.go
Labels: no changelog

#1167 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1172 microsoft.kata-image: refactor, fix reproducibility issue
  packages/by-name/microsoft/kata-image/package.nix
Labels: bug fix

#1173 docs: disable SSH access to AKS nodes
  docs/docs/getting-started/cluster-setup.md
  packages/create-coco-aks.sh
Labels: documentation

#1140 initializer/cryptsetup: rework bash entrypoint
  internal/kuberesource/parts.go
Labels: no changelog

#1163 mount: merge mounting code
  coordinator/main.go
  coordinator/mount.go
  internal/mount/mount.go
  internal/mount/mount_test.go
Labels: changelog

#1151 e2e: prevent download of streamed log directory
  .github/workflows/e2e.yml
  .github/workflows/e2e_aks_runtime.yml
  packages/scripts.nix
Labels: no changelog

#1177 kuberesource: use only PVC wrapper
  internal/kuberesource/parts.go
  internal/kuberesource/sets.go
Labels: no changelog

#1136 e2e: add GPU test
  .github/workflows/e2e_manual.yml
  .github/workflows/e2e_nightly.yml
  e2e/gpu/gpu_test.go
  e2e/gpu/testdata/gpu-pod.yaml
  e2e/internal/contrasttest/contrasttest.go
  packages/by-name/contrast/package.nix
  packages/by-name/kata/snp-launch-digest/package.nix
Labels: no changelog

#1178 deps: remove go-sev-guest replace
  go.mod
  go.sum
  packages/by-name/contrast/package.nix
Labels: dependencies

#1184 contrast.e2e: CGO_ENABLED -> env.CGO_ENABLED
  packages/by-name/contrast/package.nix
Labels: no changelog

#1183 cli: inject contrast-secrets mount into initcontainers
  internal/kuberesource/mutators.go
  internal/kuberesource/mutators_test.go
  internal/kuberesource/sets.go
Labels: bug fix

#1174 docs: add docs on GPU support
  docs/docs/basics/features.md
  docs/docs/deployment.md
  docs/docs/features-limitations.md
  docs/docs/getting-started/bare-metal.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: documentation

#1186 nodeinstaller: compare with the template file content
  nodeinstaller/node-installer.go
Labels: no changelog

#1189 e2e/runtime-reproducibility: fix teams notifications
  .github/workflows/e2e_runtime-reproducibility.yml
Labels: no changelog

#1190 e2e/runtime-reproducibility: add gpu image, don't fail fast in checksum step
  .github/workflows/e2e_runtime-reproducibility.yml
Labels: no changelog
