Repository edgelesssys/contrast, pull requests merged in 2025-06, with the labels that each got.

#1500 scripts: don't assume default namespace for renew-sync-fifo
  packages/scripts.nix
Labels: no changelog

#1501 ci: fix bugs in cluster_recreate
  .github/workflows/cluster_recreate.yml
Labels: no changelog

#1499 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1510 release: run nightly/regresssion e2e
  .github/workflows/e2e_nightly.yml
  .github/workflows/e2e_regression.yml
  .github/workflows/release.yml
Labels: no changelog

#1394 e2e/regression: add common resource types
  docs/docs/features-limitations.md
  e2e/internal/kubeclient/deploy.go
  e2e/internal/kubeclient/wait.go
  e2e/regression/README.md
  e2e/regression/regression_test.go
  e2e/regression/testdata/apache-httpd-pod.yml
  e2e/regression/testdata/config-map-immutable.yml
  e2e/regression/testdata/config-map.yml
  e2e/regression/testdata/cronjob.yml
  e2e/regression/testdata/daemonset.yml
  e2e/regression/testdata/disruption-budget.yml
  e2e/regression/testdata/job.yml
  e2e/regression/testdata/limit-range.yml
  e2e/regression/testdata/privileged-container.yml
  e2e/regression/testdata/replicaset.yml
  e2e/regression/testdata/replication-controller.yml
  e2e/regression/testdata/role.yml
  e2e/regression/testdata/rolebinding.yml
  e2e/regression/testdata/secret.yml
  e2e/regression/testdata/service.yml
  e2e/regression/testdata/serviceaccount.yml
Labels: no changelog

#1513 msft.genpolicy: correctly represent binaryData in ConfigMaps
  packages/by-name/microsoft/genpolicy/0015-genpolicy-correctly-represent-binaryData-in-ConfigMa.patch
  packages/by-name/microsoft/genpolicy/package.nix
Labels: no changelog

#1508 ci: add weekly containerd store cleanup
  .github/workflows/bm_maintenance.yml
  packages/cleanup-bare-metal.sh
  packages/containers.nix
  packages/scripts.nix
  tools/bm-maintenance/cleanup-containerd.yml
Labels: no changelog

#1526 dev-shells: add a rust dev shell for upstream work
  dev-shells/by-name/kata.nix
  flake.lock
  flake.nix
Labels: no changelog

#1538 dev-docs: update how to configure nix daemon build dir
  dev-docs/e2e/bare-metal-runner.md
Labels: no changelog

#1527 ci: only cleanup nix store if disk space is low
  packages/containers.nix
  packages/scripts.nix
  tools/bm-maintenance/nix-gc.yml
Labels: no changelog

#1528 ci: notify teams even if previous job is skipped/cancelled
  .github/workflows/bm_maintenance.yml
Labels: no changelog

#1537 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1534 docs: update links to canonical/tdx
  docs/docs/getting-started/bare-metal.md
  docs/versioned_docs/version-1.9/getting-started/bare-metal.md
Labels: documentation

#1519 kata: add patch preventing corruption of genpolicy's layer cache file
  packages/by-name/kata/kata-runtime/0026-genpolicy-keep-layers-cache-in-memory.patch
  packages/by-name/kata/kata-runtime/package.nix
  packages/by-name/microsoft/genpolicy/0016-genpolicy-prevent-corruption-of-the-layer-cache-file.patch
  packages/by-name/microsoft/genpolicy/package.nix
Labels: bug fix

#1522 e2e/regression: binaryData in ConfigMap
  e2e/regression/testdata/config-map.yml
Labels: no changelog

#1542 coordinator: don't fail liveness probe if Kubernetes API server is unavailable
  coordinator/internal/peerrecovery/recovery.go
  coordinator/internal/peerrecovery/recovery_test.go
  coordinator/internal/probes/probes.go
  coordinator/internal/probes/probes_test.go
  coordinator/main.go
Labels: bug fix

#1547 chore: add .tmp directories to gitignore
  .gitignore
Labels: no changelog

#1555 node-installer: disable config overrides via annotations
  docs/docs/features-limitations.md
  nodeinstaller/internal/kataconfig/config.go
  nodeinstaller/internal/kataconfig/testdata/expected-configuration-clh-snp.toml
  nodeinstaller/internal/kataconfig/testdata/expected-configuration-qemu-snp-gpu.toml
  nodeinstaller/internal/kataconfig/testdata/expected-configuration-qemu-snp.toml
  nodeinstaller/internal/kataconfig/testdata/expected-configuration-qemu-tdx.toml
Labels: changelog

#1553 dev-docs: update runner setup guide
  dev-docs/e2e/bare-metal-runner.md
Labels: no changelog
