Repository edgelesssys/contrast, pull requests merged in 2025-03, with the labels that each got.

#1265 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1274 e2e: increase timeout for scaling deployment in workloadsecrettest
  e2e/workloadsecret/workloadsecret_test.go
Labels: no changelog

#1269 cli: refactor coordinator policy hash injection
  cli/cmd/assets/coordinator-policy-hash
  cli/cmd/assets/coordinator-policy-hashes-fallback.json
  cli/cmd/common.go
  cli/cmd/generate.go
  cli/cmd/policies.go
  cli/cmd/recover.go
  cli/cmd/set.go
  cli/cmd/verify.go
  internal/platforms/platforms.go
  packages/by-name/cli-release/package.nix
  packages/by-name/contrast/package.nix
Labels: no changelog

#1276 nodeinstaller: support containerd config v3
  nodeinstaller/internal/constants/constants.go
  nodeinstaller/node-installer.go
Labels: bug fix, backport release/v1.5

#1251 cli: fix panic on set without workload owner key
  cli/cmd/set.go
Labels: bug fix, backport release/v1.5

#1279 [release/v1.5] cli: fix panic on set without workload owner key
  cli/cmd/set.go
Labels: bug fix

#1284 coordinator: print run error in main
  coordinator/main.go
Labels: no changelog

#1289 docs: remove mention of kernel 6.11 rcs
  docs/docs/getting-started/bare-metal.md
Labels: documentation

#1270 enterprise: add peer discovery package
  enterprise/coordinator/peerdiscovery/peerdiscovery.go
  enterprise/coordinator/peerdiscovery/peerdiscovery_test.go
  internal/kuberesource/parts.go
Labels: no changelog

#1295 renovate: don't update replaced Go import of contrast
  renovate.json5
Labels: no changelog

#1298 renovate: fix ignore of replaced Go import
  renovate.json5
Labels: no changelog

#1293 coordinator: improve shutdown behavior
  coordinator/main.go
Labels: no changelog

#1304 authority: add getters for State fields
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/authority_test.go
  coordinator/internal/authority/credentials.go
  coordinator/internal/authority/userapi.go
  coordinator/internal/meshapi/meshapi.go
  coordinator/internal/meshapi/meshapi_test.go
  coordinator/internal/transitengineapi/transitengineapi.go
  coordinator/internal/transitengineapi/transitengineapi_test.go
Labels: no changelog

#1303 manifest: add docstrings for keys
  internal/manifest/manifest.go
Labels: no changelog

#1305 e2e: include coordinator in regression test resources
  e2e/regression/regression_test.go
Labels: no changelog

#1308 authority: allow testing without embedded reference values
  coordinator/internal/authority/authority_test.go
  coordinator/internal/authority/userapi_test.go
Labels: no changelog

#1301 atls: encode nonce in ALPN protos
  internal/atls/atls.go
  internal/atls/atls_test.go
Labels: changelog

#1315 attestation: include reason for failed CRL parsing
  internal/attestation/snp/validator.go
Labels: no changelog

#1312 e2e: increase timeout for rogue pod test
  e2e/policy/policy_test.go
Labels: no changelog

#1311 retry: add a few helpers
  internal/retry/retry.go
  internal/retry/retry_test.go
Labels: no changelog

#1320 docs: correct sysctl setting recommendation
  docs/docs/getting-started/bare-metal.md
Labels: documentation

#1322 docs: fix curl flags
  docs/docs/deployment.md
  docs/docs/examples/emojivoto.md
  docs/docs/examples/mysql.md
Labels: no changelog

#1313 e2e: use retry package for kubeclient.WaitFor
  e2e/internal/kubeclient/deploy.go
Labels: no changelog

#1282 manifest: join validation errors and return late
  internal/manifest/manifest.go
Labels: changelog
