Repository edgelesssys/contrast, pull requests merged in 2025-07, with the labels that each got.

#1557 overlays: update libnvidia-container patch
  overlays/nixpkgs.nix
Labels: no changelog

#1550 e2e/regression: remove unnecessary TODO comment
  e2e/regression/testdata/config-map-immutable.yml
Labels: no changelog

#1560 coordinator: don't fail liveness probe if Kubernetes API server is unavailable (reapply)
  coordinator/internal/peerrecovery/recovery.go
  coordinator/internal/peerrecovery/recovery_test.go
  coordinator/internal/probes/probes.go
  coordinator/internal/probes/probes_test.go
  coordinator/main.go
  internal/kuberesource/parts.go
Labels: no changelog

#1565 initializer: create /run directory for cryptsetup
  initializer/main.go
Labels: no changelog

#1575 [release/v1.9] initializer: create /run directory for cryptsetup
  initializer/main.go
Labels: no changelog

#1573 gpu: pin nvidia driver to 570.158.01
  packages/nixos/gpu.nix
Labels: changelog

#1571 e2e/gpu: check for mounted libs/binaries
  e2e/gpu/gpu_test.go
Labels: no changelog

#1578 docs: revise features and limitations
  docs/docs/architecture/components/coordinator.md
  docs/docs/architecture/features-limitations.md
Labels: documentation

#1581 docs: clarify expectations on Coordinator readiness
  docs/docs/architecture/components/coordinator.md
  docs/docs/architecture/components/initializer.md
  docs/docs/getting-started/deployment.md
  docs/docs/howto/workload-deployment/deploy-application.md
Labels: documentation

#1587 docs: expand peer recovery description and how-to
  docs/docs/architecture/components/coordinator.md
  docs/docs/howto/coordinator-ha.md
Labels: documentation

#1590 docs: add supported processor families
  docs/docs/howto/cluster-setup/bare-metal.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: documentation

#1591 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1569 ci: add cleanup-namespaces job to aks ci cluster
  .github/workflows/bm_maintenance.yml
Labels: no changelog

#1559 just: acquire fifo ticket for gpu platform
  .github/workflows/bm_maintenance.yml
  .github/workflows/e2e.yml
  justfile
  packages/cleanup-namespaces.sh
  packages/scripts.nix
  tools/bm-maintenance/cleanup-namespaces.yml
Labels: no changelog

#1595 docs: gettings-started without vanilla emojivoto yaml
  docs/docs/getting-started/deployment.md
Labels: no changelog

#1596 docs: revise runtimeClass and resources
  docs/docs/getting-started/deployment.md
  docs/docs/getting-started/overview.md
  docs/docs/howto/workload-deployment/deployment-file-preparation.md
Labels: no changelog

#1602 ci: fix nix build dir setup after update to nix 2.30
  .github/actions/setup_nix/action.yml
Labels: no changelog

#1608 ci: trigger regression test on Kata changes
  .github/workflows/e2e_regression.yml
Labels: no changelog

#1607 docs: add network usage recommendations
  docs/docs/howto/hardening.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: documentation

#1603 ci: don't run docs-publish on PRs from forks
  .github/workflows/docs_publish.yml
Labels: no changelog

#1614 kuberesource: add memory limit to volumestatefulset
  internal/kuberesource/sets.go
Labels: no changelog

#1618 ci: fix docs build on main
  .github/workflows/docs_publish.yml
Labels: no changelog

#1610 docs: CPU limit usage
  docs/docs/howto/workload-deployment/deployment-file-preparation.md
Labels: documentation

#1609 nodeinstaller: automatically update testdata on kata config update
  nodeinstaller/internal/kataconfig/update-testdata/main.go
  packages/scripts.nix
Labels: no changelog

#1623 flake: remove renovate comment
  flake.nix
Labels: no changelog

#1624 initializer: wait less between cert requests
  initializer/main.go
Labels: changelog

#1625 ci: ubuntu-22.04 -> ubuntu-24.04
  .github/workflows/asciinema.yml
  .github/workflows/backport.yml
  .github/workflows/bm_maintenance.yml
  .github/workflows/check_patches.yml
  .github/workflows/cluster_recreate.yml
  .github/workflows/docs_publish.yml
  .github/workflows/e2e_aks_runtime.yml
  .github/workflows/e2e_manual.yml
  .github/workflows/e2e_nightly.yml
  .github/workflows/e2e_on_pull_request.yml
  .github/workflows/e2e_regression.yml
  .github/workflows/e2e_runtime-reproducibility.yml
  .github/workflows/e2e_service_mesh.yml
  .github/workflows/release.yml
  .github/workflows/release_publish.yml
  .github/workflows/require_label.yml
  .github/workflows/rim_updates.yml
  .github/workflows/rpm_updates.yml
  .github/workflows/static.yml
  .github/workflows/update_bm_tcb_specs.yml
Labels: no changelog

#1630 packages: remove protoc-gen-go-ttrpc
  packages/by-name/protoc-gen-go-ttrpc/package.nix
Labels: no changelog

#1633 dev-shells: make kata shell work for cdh
  dev-shells/by-name/kata.nix
Labels: no changelog

#1631 docs/how-to/generate: rework initializer section; add sec about service mesh injection
  docs/docs/howto/workload-deployment/TLS-configuration.md
  docs/docs/howto/workload-deployment/generate-annotations.md
Labels: no changelog

#1637 e2e/gpu: fix handling of empty ls stdout
  e2e/gpu/gpu_test.go
Labels: no changelog

#1635 e2e/aks-runtime: install openssl-1.1
  .github/workflows/e2e_aks_runtime.yml
Labels: no changelog

#1634 imagepuller: add flag for setting tempdir location
  imagepuller/go.mod
  imagepuller/go.sum
  imagepuller/main.go
  packages/by-name/imagepuller/package.nix
Labels: no changelog

#1641 docs: remove link to pr-preview dir
  docs/README.md
Labels: no changelog

#1646 ci: set branch for rim/rpm update PRs
  .github/workflows/rim_updates.yml
  .github/workflows/rpm_updates.yml
Labels: no changelog

#1645 dev-docs: update NVIDIA RIM IDs
  dev-docs/nvidia/rim-ids.json
Labels: no changelog

#1549 e2e/regression: extend test for secrets and config maps
  e2e/regression/testdata/pod-secret-and-cm/cm.yml
  e2e/regression/testdata/pod-secret-and-cm/pod.yml
  e2e/regression/testdata/pod-secret-and-cm/secret.yml
Labels: no changelog

#1655 docs: backport aTLS docs to v1.11
  docs/versioned_docs/version-1.11/architecture/attestation/atls.md
  docs/versioned_sidebars/version-1.11-sidebars.json
Labels: no changelog
