Repository edgelesssys/contrast, pull requests merged in 2025-02, with the labels that each got.

#1200 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1182 kata.kata-runtime: 3.12.0 -> 3.13.0
  packages/by-name/kata/kata-kernel-uvm/package.nix
  packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
  packages/by-name/kata/kata-runtime/0018-agent-remove-CDI-support.patch
  packages/by-name/kata/kata-runtime/0018-runtime-use-actual-booleans-for-QMP-device_add-boole.patch
  packages/by-name/kata/kata-runtime/0019-genpolicy-support-dynamic-annotations.patch
  packages/by-name/kata/kata-runtime/0020-agent-clear-log-pipes-if-denied-by-policy.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: changelog

#1206 nodeinstaller: ignore absence of containerd config template
  nodeinstaller/node-installer.go
Labels: bug fix, backport release/v1.4

#1205 fix: add '/run' volume to initializer
  packages/containers.nix
Labels: bug, no changelog

#1207 [release/v1.4] nodeinstaller: ignore absence of containerd config template
  nodeinstaller/node-installer.go
Labels: bug fix

#1213 coordinator: handle signals
  coordinator/main.go
Labels: no changelog

#1211 containers: reduce image size of initializer and coordinator
  packages/containers.nix
Labels: no changelog

#1215 just: bump SNP Kubeconfig secret version
  justfile
Labels: no changelog

#1218 deps: update go-sev-guest to v0.0.0-20250207111439-8e37ee550a38
  go.mod
  go.sum
  packages/by-name/contrast/package.nix
Labels: dependencies

#1217 docs: bare-metal runner specs
  dev-docs/e2e/bare-metal-runner.md
  dev-docs/e2e/tcb-specs.json
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#1219 e2e: increase wait time for nodeinstaller
  e2e/internal/contrasttest/contrasttest.go
Labels: no changelog

#1191 internal/testkeys: use fixed keys in unit tests
  coordinator/history/history_test.go
  coordinator/internal/authority/userapi_test.go
  internal/atls/atls_test.go
  internal/ca/ca_test.go
  internal/manifest/crypto_test.go
  internal/testkeys/testkeys.go
Labels: no changelog

#1204 rfc: add secure pv injection rfc
  rfc/009-secure-pv-injection.md
Labels: no changelog

#1216 packages/kata-runtime: allow arbitrary CDI annotations
  packages/by-name/kata/kata-runtime/0018-agent-remove-CDI-support.patch
  packages/by-name/kata/kata-runtime/0018-genpolicy-support-dynamic-annotations.patch
  packages/by-name/kata/kata-runtime/0019-agent-clear-log-pipes-if-denied-by-policy.patch
  packages/by-name/kata/kata-runtime/0020-runtime-remove-CDI-annotations.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: no changelog

#1209 cli/generate: add flag for output file
  cli/cmd/generate.go
Labels: changelog

#1221 docs: point to nvidia-ctk for CDI generation
  docs/docs/getting-started/bare-metal.md
Labels: no changelog

#1222 docs: document incompatibility with non-CC GPUs
  docs/docs/getting-started/bare-metal.md
  packages/nixos/gpu.nix
Labels: documentation

#1225 ci: cancel old workflow runs on push
  .github/workflows/e2e_on_pull_request.yml
Labels: no changelog

#1224 runtime: derive handler from version
  packages/by-name/kata/contrast-node-installer-image/package.nix
  packages/by-name/microsoft/contrast-node-installer-image/package.nix
Labels: bug fix

#1231 cli: don't panic on absent pod template metadata
  cli/cmd/generate.go
  cli/cmd/generate_test.go
Labels: bug fix

#1233 e2e: use correct testing context in policy test
  e2e/policy/policy_test.go
Labels: no changelog

#1234 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1226 dev-docs: document KDS caching
  dev-docs/kds.drawio.svg
  dev-docs/kds.md
  internal/attestation/snp/issuer/issuer.go
  internal/attestation/snp/validator.go
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#1223 cli/generate: automatic cryptsetup configuration
  docs/docs/architecture/secrets.md
  initializer/main.go
  initializer/mount.go
  internal/kuberesource/mutators.go
  internal/kuberesource/mutators_test.go
  internal/kuberesource/sets.go
Labels: changelog

#1236 kuberesource: increase memory limit for emojivoto with mesh
  internal/kuberesource/sets.go
Labels: no changelog

#1238 attestation: get product from attestation instead of report
  internal/attestation/snp/validator.go
Labels: changelog, backport release/v1.5

#1240 [release/v1.5] attestation: get product from attestation instead of report
  internal/attestation/snp/validator.go
Labels: changelog

#1241 [release/v1.5] grpc: retry connecting to coordinator on EOF
  internal/grpc/retry/retry.go
  internal/grpc/retry/retry_test.go
Labels: bug fix

#1078 rfc: distributed coordinator
  rfc/010-distributed-coordinator.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#1245 docs: troubleshooting CLI connection errors
  docs/docs/troubleshooting.md
Labels: documentation

#1248 atls: forward context to validators
  internal/atls/atls.go
  internal/atls/atls_test.go
  internal/attestation/snp/validator.go
  internal/attestation/tdx/validator.go
  internal/grpc/atlscredentials/atlscredentials.go
Labels: no changelog

#1247 kata.genpolicy: fail when layer can't be processed
  packages/by-name/kata/kata-runtime/0021-genpolicy-fail-when-layer-can-t-be-processed.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: changelog

#1257 ci: require "snp-gpu" tag for SNP-GPU platform
  .github/workflows/e2e_nightly.yml
Labels: no changelog

#1256 just: add kubeconfig of new SNP CI server
  justfile
Labels: no changelog

#1262 docs: point to latest longhorn docs
  docs/docs/getting-started/bare-metal.md
Labels: no changelog

#1254 genpolicy: support ephemeral volume source on bare metal
  e2e/regression/testdata/ephemeral-volume.yml
  packages/by-name/kata/kata-runtime/0022-genpolicy-support-ephemeral-volume-source.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: bug fix
