Repository edgelesssys/contrast, pull requests merged in 2025-08, with the labels that each got.

#1654 imagepuller: refactor and better error handling
  imagepuller/internal/service/verify.go
  imagepuller/internal/service/verify_test.go
Labels: no changelog

#1666 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1668 nixos: add empty /etc/machine-id
  packages/nixos/system.nix
Labels: no changelog

#1652 ci: imagepuller-benchmark
  .github/workflows/imagepuller-benchmark.yml
  go.work
  imagepuller/client/client.go
  packages/by-name/imagepuller-benchmark/package.nix
  renovate.json5
  tools/imagepuller-benchmark/go.mod
  tools/imagepuller-benchmark/go.sum
  tools/imagepuller-benchmark/main.go
Labels: no changelog

#1672 ci: fix imagepuller-benchmark go module
  packages/by-name/imagepuller-benchmark/package.nix
  tools/imagepuller-benchmark/go.mod
  tools/imagepuller-benchmark/go.sum
Labels: no changelog

#1674 genpolicy: support AddARPNeighbors
  packages/by-name/kata/kata-runtime/0024-genpolicy-add-rule-for-AddARPNeighbors.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: changelog

#1678 ci: do not fail imagepuller-benchmark due to time delta
  imagepuller/client/client.go
  tools/imagepuller-benchmark/main.go
Labels: no changelog

#1680 docs: fix broken platformInfo struct table
  docs/docs/architecture/attestation/amd-details.md
  docs/versioned_docs/version-1.11/architecture/attestation/amd-details.md
Labels: documentation

#1683 dev-docs: update NVIDIA RIM IDs
  dev-docs/nvidia/rim-ids.json
Labels: no changelog

#1688 snp: add support for attestation report v5
  go.mod
  go.sum
  packages/by-name/contrast/package.nix
Labels: changelog

#1690 treewide: disallow unknown fields for embedded
  internal/manifest/referencevalues.go
  nodeinstaller/internal/kataconfig/config.go
Labels: no changelog

#1698 renovate: fix imagepuller ignore
  renovate.json5
Labels: no changelog

#1712 overlays/cryptsetup: 2.8.0 -> 2.8.1
  overlays/nixpkgs.nix
Labels: changelog, backport release/v1.12

#1714 [release/v1.12] overlays/cryptsetup: 2.8.0 -> 2.8.1
  overlays/nixpkgs.nix
Labels: changelog

#1711 docs: remove reference to contrast being open source
  docs/docusaurus.config.js
Labels: no changelog

#1720 docs: remove manual cryptsetup via initializer
  docs/docs/architecture/secrets.md
Labels: documentation

#1723 service-mesh: use envoy-bin package
  packages/containers.nix
Labels: no changelog

#1715 internal/manifest: skip runtime handler test without embedded values
  internal/manifest/runtimehandler_test.go
Labels: no changelog

#1716 e2e/openssl: check for dmesg errors
  e2e/openssl/openssl_test.go
Labels: no changelog

#1728 docs: sync missing reference sections
  docs/docs/getting-started/deployment.md
  docs/docs/howto/encrypted-storage.md
Labels: no changelog
