Repository edgelesssys/contrast, pull requests merged in 2025-04, with the labels that each got.

#1330 kata.kata-kernel-uvm: 6.11 -> 6.12.13, unvendor patch
  packages/by-name/kata/kata-kernel-uvm/package.nix
  packages/by-name/kata/kata-kernel-uvm/work-around-the-segfault-issue-in-glibc-2-35.patch
Labels: dependencies

#1331 azure-ci-rg-cleanup: don't fail when no resources to delete
  packages/by-name/azure-ci-rg-cleanup/cleanup.sh
Labels: no changelog

#1334 kata.kata-runtime: 3.14.0 -> 3.15.0
  packages/by-name/kata/genpolicy/genpolicy_settings_coordinator.patch
  packages/by-name/kata/genpolicy/genpolicy_settings_dev.patch
  packages/by-name/kata/genpolicy/genpolicy_settings_prod.patch
  packages/by-name/kata/genpolicy/package.nix
  packages/by-name/kata/kata-agent/package.nix
  packages/by-name/kata/kata-kernel-uvm/package.nix
  packages/by-name/kata/kata-runtime/0001-emulate-CPU-model-that-most-closely-matches-the-host.patch
  packages/by-name/kata/kata-runtime/0002-runtime-agent-verify-the-agent-policy-hash.patch
  packages/by-name/kata/kata-runtime/0003-genpolicy-enable-sysctl-checks.patch
  packages/by-name/kata/kata-runtime/0003-genpolicy-read-bundle-id-from-rootfs.patch
  packages/by-name/kata/kata-runtime/0004-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
  packages/by-name/kata/kata-runtime/0005-genpolicy-rules-remove-check-for-OCI-version.patch
  packages/by-name/kata/kata-runtime/0006-genpolicy-settings-change-cpath-for-Nydus-guest-pull.patch
  packages/by-name/kata/kata-runtime/0007-genpolicy-allow-image_guest_pull.patch
  packages/by-name/kata/kata-runtime/0008-runtime-agent-mounts-Mount-configfs-into-the-contain.patch
  packages/by-name/kata/kata-runtime/0009-genpolicy-support-mount-propagation-and-ro-mounts.patch
  packages/by-name/kata/kata-runtime/0010-genpolicy-bump-oci-distribution-to-v0.12.0.patch
  packages/by-name/kata/kata-runtime/0010-tools-don-t-clean-build-root-when-generating-rootfs.patch
  packages/by-name/kata/kata-runtime/0011-runtime-allow-initrd-AND-image-to-be-set.patch
  packages/by-name/kata/kata-runtime/0012-genpolicy-do-not-log-policy-annotation-in-debug.patch
  packages/by-name/kata/kata-runtime/0013-genpolicy-allow-non-watchable-ConfigMaps.patch
  packages/by-name/kata/kata-runtime/0014-genpolicy-support-guest-hooks.patch
  packages/by-name/kata/kata-runtime/0015-genpolicy-support-dynamic-annotations.patch
  packages/by-name/kata/kata-runtime/0016-runtime-remove-CDI-annotations.patch
  packages/by-name/kata/kata-runtime/0017-genpolicy-support-ephemeral-volume-source.patch
  packages/by-name/kata/kata-runtime/0018-agent-clear-log-pipes-if-denied-by-policy.patch
  packages/by-name/kata/kata-runtime/0020-runtime-make-SNP-IDBlock-configurable.patch
  packages/by-name/kata/kata-runtime/0021-genpolicy-fail-when-layer-can-t-be-processed.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: changelog

#1263 dev-docs: document setup of bare-metal CI runner
  dev-docs/e2e/bare-metal-runner.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#1261 attestation: forward context to KDS getter
  internal/attestation/certcache/cached_client.go
  internal/attestation/certcache/cached_client_test.go
Labels: no changelog

#1342 e2e/release: fix patching of reference values
  e2e/internal/contrasttest/contrasttest.go
  e2e/release/release_test.go
Labels: no changelog

#1340 kata: disable genpolicy integration tests
  packages/by-name/kata/genpolicy/package.nix
Labels: no changelog

#1336 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1310 meshapi: add recover handler
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/userapi.go
  coordinator/internal/meshapi/meshapi.go
  coordinator/internal/meshapi/meshapi_test.go
  coordinator/internal/seedengine/seedengine.go
  coordinator/internal/transitengineapi/transitengineapi_test.go
  internal/ca/ca.go
  internal/meshapi/meshapi.pb.go
  internal/meshapi/meshapi.proto
  internal/meshapi/meshapi_grpc.pb.go
Labels: no changelog

#1335 history: allow insecure access to the latest transition
  coordinator/history/history.go
  coordinator/history/history_test.go
Labels: no changelog, needs: review

#1341 seedengine: move to the root internal package
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/userapi.go
  coordinator/internal/meshapi/meshapi_test.go
  coordinator/internal/transitengineapi/transitengineapi_test.go
  internal/seedengine/seedengine.go
  internal/seedengine/seedengine_test.go
Labels: no changelog

#1347 manifest: validate guest policy
  coordinator/internal/authority/authority_test.go
  internal/manifest/manifest_test.go
  internal/manifest/referencevalues.go
Labels: changelog

#1358 coordinator: make KDS cache shareable
  coordinator/internal/authority/credentials.go
  coordinator/main.go
Labels: no changelog

#1355 docs: improve language of SNP attestation
  docs/docs/architecture/snp.md
  docs/sidebars.js
  docs/versioned_docs/version-1.7/architecture/snp.md
  docs/versioned_sidebars/version-1.7-sidebars.json
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#1368 ci: make check green on prs without do-not-merge label
  .github/workflows/require_label.yml
Labels: no changelog

#1364 node-installer: fix timestamp precision in unit restart detection
  go.mod
  go.sum
  internal/kuberesource/parts.go
  nodeinstaller/node-installer.go
  packages/by-name/contrast/package.nix
Labels: bug fix

#1369 docs: troubleshoot containerd pulling wrong image refs
  docs/docs/troubleshooting.md
Labels: documentation

#1378 dev-docs: add KUBECONFIG export
  dev-docs/e2e/bare-metal-runner.md
Labels: no changelog

#1349 meshapi: add workload secret as extension
  coordinator/internal/meshapi/meshapi.go
  internal/attestation/extension/extension.go
  internal/oid/oid.go
Labels: no changelog

#1379 ci: fix teams notifications
  .github/workflows/e2e.yml
Labels: no changelog

#1346 transitengineapi: tls client cert auth
  coordinator/internal/transitengineapi/transitengineapi.go
  internal/ca/ca.go
Labels: no changelog

#1376 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1348 transitengineapi: mTLS with client authorization by workloadSecret
  coordinator/internal/transitengineapi/transitengineapi.go
  coordinator/internal/transitengineapi/transitengineapi_test.go
Labels: no changelog

#1343 nodeinstaller: backup existing containerd config
  docs/docs/components/runtime.md
  nodeinstaller/node-installer.go
Labels: changelog

#1383 genpolicy: allow sysfs RW mount for pause container
  packages/by-name/kata/kata-runtime/0018-genpolicy-allow-RO-and-RW-for-sysfs-with-privileged-.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: no changelog

#1371 coordinator: fix race condition in authority test
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/authority_test.go
Labels: no changelog

#1390 ci: use the right GPU runner for manual tests
  .github/workflows/e2e_manual.yml
Labels: no changelog

#1391 transitengineapi: activate and expose in coordinator
  coordinator/internal/transitengineapi/transitengineapi.go
  coordinator/main.go
Labels: changelog

#1392 transitengineapi: coding style and comments
  coordinator/internal/transitengineapi/transitengineapi.go
Labels: no changelog

#1395 coordinator: fix TestRecovery overrides
  coordinator/internal/authority/userapi_test.go
Labels: no changelog, needs: rework

#1389 sdk: take cache as input for ValidatorsFromManifest
  cli/cmd/common.go
  cli/cmd/recover.go
  cli/cmd/set.go
  sdk/common.go
  sdk/verify.go
Labels: no changelog

#1350 coordinator: move WalkTransitions function to history package
  coordinator/history/history.go
  coordinator/history/history_test.go
  coordinator/internal/authority/authority.go
  coordinator/internal/authority/userapi.go
Labels: no changelog

#1411 e2e: print stdout on gpu test error
  e2e/gpu/gpu_test.go
Labels: no changelog

#1354 ci: periodically update kubernetes resources
  .github/workflows/update_ci_resources.yml
Labels: no changelog, needs: review

#1402 tools/bm-maintenance: support containerd config v3 in cleanup
  packages/cleanup-bare-metal.sh
Labels: no changelog

#1412 e2e: skip log download if no namespace file exists
  packages/scripts.nix
Labels: no changelog

#1418 e2e/workloadsecret: require first secret to be present
  e2e/workloadsecret/workloadsecret_test.go
Labels: no changelog

#1414 dev-docs: document EKS hybrid nodes
  dev-docs/eks/hybrid-nodes/README.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#1422 scripts.generate: sync go directive after each tidy
  packages/scripts.nix
Labels: no changelog

#1425 e2e/aks-runtime: print az extensions
  .github/workflows/e2e_aks_runtime.yml
Labels: no changelog
