Repository edgelesssys/contrast, pull requests merged in 2025-09, with the labels that each got.

#1739 dev-docs: add guidance for working with GHSAs
  dev-docs/ghsa.md
Labels: no changelog

#1746 dev-docs: update NVIDIA RIM IDs
  dev-docs/nvidia/rim-ids.json
Labels: no changelog

#1663 imagepuller: add unit tests
  imagepuller/internal/remote/remote.go
  imagepuller/internal/service/service.go
  imagepuller/internal/service/stubs_test.go
  imagepuller/internal/service/verify.go
  imagepuller/internal/service/verify_test.go
  imagepuller/internal/test/registry/content.go
  imagepuller/main.go
Labels: no changelog

#1717 cli/verifier: check servicemesh-egress annotation isn't empty
  cli/verifier/servicemesh_egress.go
  cli/verifier/servicemesh_egress_test.go
  cli/verifier/verifiers.go
Labels: changelog

#1751 docs: warn about usage of kubectl apply -n
  docs/docs/howto/workload-deployment/deploy-application.md
Labels: documentation

#1755 cli/verify: unzip policy files
  cli/cmd/verify.go
Labels: bug fix

#1757 just: apply node-installer target config before runtime
  justfile
Labels: no changelog

#1762 node-installer/update-testdata: don't fail on changes
  nodeinstaller/internal/kataconfig/update-testdata/main.go
Labels: no changelog

#1765 contrast-releases: fix runtime existence
  packages/contrast-releases.nix
Labels: no changelog

#1766 e2e/release: use node-installer target config
  .github/workflows/release.yml
  e2e/release/release_test.go
Labels: no changelog

#1767 kuberesource: default target config to kube-system namespace
  e2e/internal/contrasttest/contrasttest.go
  internal/kuberesource/mutators.go
  internal/kuberesource/parts.go
  internal/kuberesource/resourcegen/main.go
Labels: no changelog

#1769 ci: remove imagestore from e2e regression
  .github/workflows/e2e_regression.yml
Labels: no changelog

#1770 dev-docs: update NVIDIA RIM IDs
  dev-docs/nvidia/rim-ids.json
Labels: no changelog

#1749 ci/regression: add memory limit test
  e2e/regression/testdata/memory-limit/memory-limit.yml
Labels: no changelog

#1772 ci/sync: upgrade sync server to improve logging
  .github/workflows/bm_maintenance.yml
Labels: no changelog

#1771 cli/initdata: init initdata lib
  internal/initdata/initdata.go
  internal/initdata/initdata_test.go
Labels: no changelog

#1776 ci/bm-maintenance: upgrade sync-server
  .github/workflows/bm_maintenance.yml
Labels: no changelog

#1802 packages/nixos: prefix debug tools with contrastPkgs
  packages/nixos/debug.nix
Labels: no changelog

#1801 e2e: add openssl logging for unexpected success
  e2e/openssl/openssl_test.go
Labels: no changelog

#1805 just: pass platform to apply
  justfile
Labels: no changelog

#1806 just: write platform to justfile.env
  justfile
Labels: no changelog

#1811 snp: remove THIM getter
  internal/attestation/snp/issuer/issuer.go
  internal/attestation/snp/issuer/thim.go
Labels: no changelog
