Repository edgelesssys/contrast, pull requests merged in 2025-05, with the labels that each got.

#1426 codeowners: remove 3u13r
  .github/CODEOWNERS
Labels: no changelog

#1428 e2e/reproducibility: upgrade ubuntu from 20.04 to 24.04
  .github/workflows/e2e_runtime-reproducibility.yml
Labels: no changelog

#1413 e2e: better logging in aks runtime test
  e2e/aks-runtime/aks_runtime_test.go
  e2e/internal/az/aks.go
Labels: no changelog

#1423 microsoft.kata-runtime: 3.2.0.azl4 -> 3.2.0.azl5
  packages/by-name/microsoft/genpolicy/0001-genpolicy-add-rules-and-types-for-volumeDevices.patch
  packages/by-name/microsoft/genpolicy/0002-genpolicy-add-ability-to-filter-for-runtimeClassName.patch
  packages/by-name/microsoft/genpolicy/0003-genpolicy-allow-specifying-layer-cache-file.patch
  packages/by-name/microsoft/genpolicy/0004-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
  packages/by-name/microsoft/genpolicy/0005-genpolicy-propagate-mount_options-for-empty-dirs.patch
  packages/by-name/microsoft/genpolicy/0006-genpolicy-support-HostToContainer-mount-propagation.patch
  packages/by-name/microsoft/genpolicy/0007-genpolicy-support-for-VOLUME-definition-in-container.patch
  packages/by-name/microsoft/genpolicy/0008-genpolicy-include-reference-in-logs-when-auth-failur.patch
  packages/by-name/microsoft/genpolicy/0010-genpolicy-support-mount-propagation-and-ro-mounts.patch
  packages/by-name/microsoft/genpolicy/genpolicy_msft_settings_coordinator.patch
  packages/by-name/microsoft/genpolicy/genpolicy_msft_settings_dev.patch
  packages/by-name/microsoft/genpolicy/package.nix
  packages/by-name/microsoft/kata-agent/package.nix
  packages/by-name/microsoft/kata-runtime/0001-agent-clear-log-pipes-if-denied-by-policy.patch
  packages/by-name/microsoft/kata-runtime/package.nix
Labels: changelog

#1431 microsoft.genpolicy: fix interactive exec
  packages/by-name/microsoft/genpolicy/0011-genpolicy-match-sandbox-name-by-regex.patch
  packages/by-name/microsoft/genpolicy/package.nix
Labels: no changelog

#1314 dev-docs: add security overview
  dev-docs/security-overview.md
Labels: no changelog

#1435 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1437 kata: remove unneeded tools patch
  packages/by-name/kata/kata-runtime/0010-runtime-allow-initrd-AND-image-to-be-set.patch
  packages/by-name/kata/kata-runtime/0010-tools-don-t-clean-build-root-when-generating-rootfs.patch
  packages/by-name/kata/kata-runtime/0011-genpolicy-do-not-log-policy-annotation-in-debug.patch
  packages/by-name/kata/kata-runtime/0012-genpolicy-allow-non-watchable-ConfigMaps.patch
  packages/by-name/kata/kata-runtime/0013-genpolicy-support-guest-hooks.patch
  packages/by-name/kata/kata-runtime/0014-genpolicy-support-dynamic-annotations.patch
  packages/by-name/kata/kata-runtime/0015-runtime-remove-CDI-annotations.patch
  packages/by-name/kata/kata-runtime/0016-genpolicy-support-ephemeral-volume-source.patch
  packages/by-name/kata/kata-runtime/0017-genpolicy-allow-RO-and-RW-for-sysfs-with-privileged-.patch
  packages/by-name/kata/kata-runtime/0018-runtime-add-option-to-force-guest-pull.patch
  packages/by-name/kata/kata-runtime/package.nix
Labels: no changelog

#1438 e2e/reproducibility: fix notifications
  .github/workflows/e2e_runtime-reproducibility.yml
Labels: no changelog

#1444 release: upload artifacts into public bucket
  .github/workflows/release.yml
  .github/workflows/release_publish.yml
Labels: no changelog

#1445 ci: check licenses of Go dependencies
  .github/workflows/static.yml
  packages/scripts.nix
Labels: no changelog

#1447 microsoft.genpolicy: fix sandbox name regex match patch
  packages/by-name/microsoft/genpolicy/0011-genpolicy-match-sandbox-name-by-regex.patch
Labels: no changelog

#1441 contributing: update with commit conventions
  CONTRIBUTING.md
  tools/vale/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#1452 fix: correct manifest generation for CronJob
  cli/cmd/policies.go
Labels: no changelog

#1453 deps: update pinned rpm packages
  packages/by-name/microsoft/kata-image/package-index.json
Labels: dependencies

#1457 docs: fix mixed up SNP ABI_MINOR of CLH and QEMU
  docs/docs/architecture/snp.md
  docs/versioned_docs/version-1.7/architecture/snp.md
  docs/versioned_docs/version-1.8/architecture/snp.md
Labels: no changelog

#1454 [release/v1.8] cli: correct manifest generation for CronJob
  cli/cmd/policies.go
Labels: bug fix

#1430 cli: sensible error message if coordinator doesn't meet expectations
  cli/cmd/set.go
Labels: no changelog, needs: rework

#1467 coordinator: consider instances with stale or no manifests unready
  docs/docs/deployment.md
  e2e/internal/contrasttest/contrasttest.go
  e2e/internal/kubeclient/wait.go
  e2e/openssl/openssl_test.go
  e2e/release/release_test.go
  internal/kuberesource/parts.go
  internal/kuberesource/sets.go
  justfile
  packages/scripts.nix
Labels: breaking change

#1470 treewide: prefer [[ over [ in shell scripts
  packages/by-name/boot-microvm/package.nix
  packages/by-name/buildGoTest/package.nix
  packages/by-name/microsoft/kata-image/buildimage.sh
  packages/cleanup-bare-metal.sh
  packages/debug-qemu-tdx.sh
  packages/kata-debug-shell.sh
  packages/scripts.nix
Labels: no changelog

#1471 just: don't assume default namespace
  justfile
Labels: no changelog

#1473 scripts.get-logs: retry kubectl commands
  packages/scripts.nix
Labels: no changelog

#1474 kubeclient: ignore terminating pods
  e2e/internal/kubeclient/deploy.go
  e2e/internal/kubeclient/kubeclient.go
  e2e/internal/kubeclient/wait.go
Labels: no changelog

#1475 deps: patch go-sev-guest with AMD Siena support
  go.mod
  go.sum
  packages/by-name/contrast/package.nix
Labels: changelog, backport release/v1.8

#1476 [release/v1.8] deps: patch go-sev-guest with AMD Siena support
  go.mod
  go.sum
  packages/by-name/contrast/package.nix
Labels: changelog

#1477 microsoft.genpolicy: fix sandbox-name policy for pod controllers
  packages/by-name/microsoft/genpolicy/0011-genpolicy-match-sandbox-name-by-regex.patch
  packages/by-name/microsoft/genpolicy/0013-genpolicy-don-t-overwrite-env-vars-from-image.patch
Labels: bug fix, backport release/v1.8

#1478 [release/v1.8] microsoft.genpolicy: fix sandbox-name policy for pod controllers
  packages/by-name/microsoft/genpolicy/0011-genpolicy-match-sandbox-name-by-regex.patch
  packages/by-name/microsoft/genpolicy/0013-genpolicy-don-t-overwrite-env-vars-from-image.patch
Labels: bug fix

#1480 scripts.update-release-urls: fix escaping of tag regex
  packages/scripts.nix
Labels: no changelog

#1483 release: improve git cleaning between steps
  .github/workflows/release.yml
Labels: no changelog

#1488 Revert "deps: patch go-sev-guest with AMD Siena support"
  go.mod
  go.sum
  packages/by-name/contrast/package.nix
Labels: no changelog, backport release/v1.8

#1489 [release/v1.8] Revert "deps: patch go-sev-guest with AMD Siena support"
  go.mod
  go.sum
  packages/by-name/contrast/package.nix
Labels: no changelog

#1490 initializer: safer data handling for encrypted mount
  internal/mount/mount.go
Labels: bug fix, backport release/v1.8

#1492 [release/v1.8] initializer: safer data handling for encrypted mount
  internal/mount/mount.go
Labels: bug fix

#1456 ci: cleanup data from already deleted runtime classes
  packages/cleanup-bare-metal.sh
Labels: no changelog

#1497 kubeclient: retry port-forward on non-wrapped EOFs
  e2e/internal/kubeclient/portforward.go
Labels: no changelog
